"""대열을 확인한다 - 무리를 여러 마리로 세우고 칠 상대를 고르는 것.

SCREEN 8 에는 픽셀 단위 오라클(verify_quest_sides)이 없다. 그래서 여기서는
**던전만 그린 화면과 대열을 얹은 화면의 차이**를 오라클로 쓴다. 칸마다 달라진
픽셀을 세면 그 자리에 몬스터가 섰는지 아닌지가 나온다. 그림이 무엇이든,
어떻게 줄었든 상관없이 "n 마리가 제 칸에 있다" 만 본다.

  layout  n = 1..4 일 때 칸 폭이 VIEW_W/n 이고 n 개 칸에만 몬스터가 있다
  dead    쓰러진 칸은 비고 나머지는 그대로다 (칸을 당겨오지 않는다)
  pick    화살표가 좌우로 돌고, 쓰러진 칸은 건너뛰고, 고른 칸이 실제로 맞는다
  die     라운드 **도중에** 쓰러지면 그 칸이 저절로 빈다 (MonDiedRedraw)

pick 이 고른 칸을 어떻게 확인하는가: HeroAttack 이 PickTarget 의 결과를 바로
TmpType 에 넣는다. 굴리기 **전**이라 빗나가도 남으므로, 굴림에 기대지 않고
확인할 수 있다. 다만 **DoAttack 에 들어가는 순간에 읽어야 한다.** MonAttack 도
같은 자리를 자기 번호로 덮으므로, 라운드가 끝난 뒤에 읽으면 마지막으로 친
몬스터의 번호가 나온다(실제로 그랬다).

  uv run python gfx/quest_row.py tcl   <작업폴더>
  uv run python gfx/quest_row.py check <작업폴더>
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SYM = os.path.join(HERE, "..", "build", "quest3.sym")

VIEW_X, VIEW_Y, VIEW_W, VIEW_H = 16, 8, 96, 96
MON_N, MON_STRIDE = 5, 4
PARTY_N, PARTY_STRIDE = 6, 32
P_DEX, P_HP, P_MAXHP, P_ATK, P_DCNT, P_DSIDE, P_DMOD = 15, 21, 22, 24, 25, 26, 27
ARROW_COL = 0xFC
ARROW_W = 12
BIG_HP = 200

# 한 칸에 몬스터가 있다고 볼 최소 픽셀 수. 가장 작은 24x24 칸도 실측 300 픽셀
# 넘게 바뀌므로 넉넉하다. 빈 칸은 0 이다.
MIN_PIX = 100


def syms():
    out = {}
    for line in io.open(SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            out[name] = int(val.strip(), 16)
    return out


def setup(S, kind, alive, hp=BIG_HP):
    """파티와 무리를 원하는 꼴로 앉힌다. alive = 살아 있는 칸의 목록."""
    w = []
    for i in range(PARTY_N):
        b = S["Party"] + i * PARTY_STRIDE
        w += ["debug write memory %d 255" % (b + P_HP),
              "debug write memory %d 255" % (b + P_MAXHP),
              "debug write memory %d 10" % (b + P_DEX),
              "debug write memory %d 40" % (b + P_ATK),    # 거의 늘 맞게
              "debug write memory %d 1" % (b + P_DCNT),
              "debug write memory %d 6" % (b + P_DSIDE),
              "debug write memory %d 0" % (b + P_DMOD)]
    for i in range(MON_N):
        b = S["Monsters"] + i * MON_STRIDE
        v = hp if i in alive else 0
        w += ["debug write memory %d %d" % (b + 0, kind),
              "debug write memory %d %d" % (b + 1, v),
              "debug write memory %d %d" % (b + 2, v)]
    return w


def dumpview(path):
    """던전 창 96 줄을 통째로 뜬다. 한 줄이 256 바이트다."""
    return ['set f [open "%s" wb]' % path,
            "fconfigure $f -translation binary",
            "puts -nonewline $f [debug read_block VRAM %d %d]"
            % (VIEW_Y * 256, VIEW_H * 256),
            "close $f"]


def key(t, mask):
    return ["after time %.2f { keymatrixdown 8 %s }" % (t, mask),
            "after time %.2f { keymatrixup   8 %s }" % (t + 0.15, mask)]


KEY_SPACE, KEY_RIGHT, KEY_LEFT = "0x01", "0x80", "0x10"

# (이름, 종류, 마릿수, 살아 있는 칸)
LAYOUT = [("n1", 0, 1, [0]),
          ("n2", 0, 2, [0, 1]),
          ("n3", 4, 3, [0, 1, 2]),
          ("n4", 2, 4, [0, 1, 2, 3]),
          ("dead", 0, 3, [0, 2])]     # 가운데가 쓰러진 채로


def write_tcl(outdir):
    S = syms()
    out = outdir.replace(chr(92), "/")

    for name, kind, count, alive in LAYOUT:
        L = ["# %s - generated by gfx/quest_row.py" % name,
             # 먼저 전투 없이 던전만 그린다 (견줄 바탕).
             "after time 6 { debug write memory %d 0 ; debug write memory %d 1 }"
             % (S["BattleOn"], S["needDraw"]),
             "after time 7.5 { %s }" % " ; ".join(dumpview("%s/%s_base.bin" % (out, name))),
             "after time 8 { %s ; debug write memory %d %d ; "
             "debug write memory %d %d ; debug write memory %d 1 ; "
             "debug write memory %d 1 }"
             % (" ; ".join(setup(S, kind, alive)), S["MonCount"], count,
                S["MonKind"], kind, S["BattleOn"], S["needDraw"]),
             "after time 9.5 {",
             "  " + "\n  ".join(dumpview("%s/%s_row.bin" % (out, name))),
             '  set g [open "%s/%s.txt" w]' % (out, name),
             '  puts $g "roww [debug read memory %d]"' % S["MonRowW"],
             '  puts $g "rown [debug read memory %d]"' % S["MonRowN"],
             "  close $g ; exit",
             "}"]
        io.open(os.path.join(outdir, name + ".tcl"), "w",
                encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 화살표 -----------------------------------------------------------
    # 가운데(1 번)가 쓰러진 셋. 오른쪽을 누르면 1 번을 건너뛰고 2 번으로 가야
    # 한다. 한 번 더 누르면 0 번으로 감기고, 왼쪽을 누르면 다시 2 번이다.
    L = ["# pick - generated by gfx/quest_row.py",
         'set ::fh [open "%s/pick.txt" w]' % out,
         "after time 6 { %s ; debug write memory %d 3 ; "
         "debug write memory %d 0 ; debug write memory %d 1 ; "
         "debug write memory %d 1 ; debug write memory %d 1 }"
         % (" ; ".join(setup(S, 0, [0, 2])), S["MonCount"], S["MonKind"],
            S["BattleOn"], S["RoundNo"], S["needDraw"])]
    L += key(7.0, KEY_SPACE)                # 라운드 시작
    L += key(8.0, KEY_SPACE)                # 명령 = ATTACK -> PickTarget
    L += ['after time 9.0 { puts $::fh "sel0 [debug read memory %d]" ; '
          'puts $::fh "arrowy [debug read memory %d]" ; '
          '%s }' % (S["MonSel"], S["ArrowY"],
                    " ; ".join(dumpview("%s/pick0.bin" % out)))]
    L += key(9.5, KEY_RIGHT)
    L += ['after time 10.5 { puts $::fh "sel1 [debug read memory %d]" ; '
          '%s }' % (S["MonSel"], " ; ".join(dumpview("%s/pick1.bin" % out)))]
    L += key(11.0, KEY_RIGHT)               # 끝을 넘어 0 번으로 감긴다
    L += ['after time 12.0 { puts $::fh "sel2 [debug read memory %d]" }' % S["MonSel"]]
    L += key(12.5, KEY_LEFT)                # 왼쪽으로 감겨 다시 2 번
    L += ['after time 13.5 { puts $::fh "sel3 [debug read memory %d]" }' % S["MonSel"]]
    # 결정한 뒤 첫 DoAttack 이 이 사람의 공격이다. 그 자리에서 TmpType 을 읽는다.
    L += ["set ::armed 0",
          "debug set_bp %d 1 { if {$::armed} { set ::armed 0 ; "
          'puts $::fh "hit [debug read memory %d]" } }'
          % (S["DoAttack"], S["TmpType"]),
          "after time 13.8 { set ::armed 1 }"]
    L += key(14.0, KEY_SPACE)               # 결정
    L += ['after time 15.5 {',
          '  puts $::fh "hp0 [debug read memory %d]"' % (S["Monsters"] + 1),
          '  puts $::fh "hp2 [debug read memory %d]"'
          % (S["Monsters"] + 2 * MON_STRIDE + 1),
          "  " + "\n  ".join(dumpview("%s/pick2.bin" % out)),
          "  close $::fh ; exit",
          "}"]
    io.open(os.path.join(outdir, "pick.tcl"), "w",
            encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 라운드 도중에 쓰러지면 --------------------------------------------
    #
    # 0 번의 HP 를 1 로 두면 첫 공격에 쓰러진다 (기본 표적이 FirstMonster 라
    # 0 번이다). 그 뒤로 **needDraw 를 건드리지 않는데도** 0 번 칸이 비어야
    # 한다. 그 일을 하는 것이 MonDiedRedraw 다 - 쓰러진 자리를 지우려면 뒤의
    # 던전 그림이 있어야 하는데 우리에게 없으니 던전부터 다시 그린다.
    #
    # 스페이스를 여러 번 눌러 여러 사람이 친다. 자연 1 은 무조건 빗나가므로
    # 한 번만 치면 스무 번에 한 번 실패하는 검사가 된다.
    L = ["# die - generated by gfx/quest_row.py",
         "after time 6 { debug write memory %d 0 ; debug write memory %d 1 }"
         % (S["BattleOn"], S["needDraw"]),
         "after time 7.0 { %s }" % " ; ".join(dumpview("%s/die_base.bin" % out)),
         "after time 7.5 { %s ; debug write memory %d 1 ; "
         "debug write memory %d 2 ; debug write memory %d 0 ; "
         "debug write memory %d 1 ; debug write memory %d 1 }"
         % (" ; ".join(setup(S, 0, [0, 1])), S["Monsters"] + 1,
            S["MonCount"], S["MonKind"], S["BattleOn"], S["RoundNo"]),
         "after time 8.0 { debug write memory %d 1 }" % S["needDraw"],
         "after time 9.0 { %s }" % " ; ".join(dumpview("%s/die_before.bin" % out))]
    t = 9.5
    while t < 15.0:                         # 스페이스를 계속 누른다
        L += key(t, KEY_SPACE)
        t += 0.6
    L += ["after time 16.0 {",
          "  " + "\n  ".join(dumpview("%s/die_after.bin" % out)),
          '  set g [open "%s/die.txt" w]' % out,
          '  puts $g "hp0 [debug read memory %d]"' % (S["Monsters"] + 1),
          '  puts $g "hp1 [debug read memory %d]"'
          % (S["Monsters"] + MON_STRIDE + 1),
          "  close $g ; exit",
          "}"]
    io.open(os.path.join(outdir, "die.tcl"), "w",
            encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote %d tcl scripts" % (len(LAYOUT) + 2))


# --------------------------------------------------------------------------


def view(path):
    """뜬 VRAM 에서 던전 창만 잘라 낸다. [y][x] 로 본다."""
    b = io.open(path, "rb").read()
    return [b[r * 256 + VIEW_X:r * 256 + VIEW_X + VIEW_W] for r in range(VIEW_H)]


def cell_diff(base, row, count):
    """칸마다 바탕과 달라진 픽셀 수."""
    w = VIEW_W // count
    out = []
    for c in range(count):
        n = 0
        for y in range(VIEW_H):
            for x in range(c * w, (c + 1) * w):
                if base[y][x] != row[y][x]:
                    n += 1
        out.append(n)
    return out


def arrow_x(path, ay):
    """ArrowY 줄의 화살표 왼쪽 끝. 없으면 None.

    **줄을 롬이 알려 준 ArrowY 로 못 박는다.** 아무 줄에서나 노란 픽셀 열두 개를
    찾으면, 나중에 몬스터 그림에 그만한 노란 줄이 생겼을 때 엉뚱한 줄을 읽고도
    조용히 통과한다.
    """
    v = view(path)
    y = ay - VIEW_Y
    xs = [x for x in range(VIEW_W) if v[y][x] == ARROW_COL]
    return min(xs) + VIEW_X if len(xs) == ARROW_W else None


def check(outdir):
    bad = 0
    for name, _kind, count, alive in LAYOUT:
        txt = dict(l.split(None, 1) for l in
                   io.open(os.path.join(outdir, name + ".txt")).read().split("\n") if l.strip())
        roww, rown = int(txt["roww"]), int(txt["rown"])
        base = view(os.path.join(outdir, name + "_base.bin"))
        row = view(os.path.join(outdir, name + "_row.bin"))
        diff = cell_diff(base, row, count)
        want_w = VIEW_W // count
        ok = (roww == want_w and rown == count
              and all((d >= MIN_PIX) == (i in alive) for i, d in enumerate(diff)))
        print("%-6s 칸 %d 개 x %2d 픽셀   칸별 바뀐 픽셀 %s   %s"
              % (name, count, roww, diff, "OK" if ok else "FAIL"))
        if not ok:
            bad += 1
            print("       바란 것: 폭 %d, 칸 수 %d, 몬스터가 선 칸 %s"
                  % (want_w, count, alive))

    txt = dict(l.split(None, 1) for l in
               io.open(os.path.join(outdir, "pick.txt")).read().split("\n") if l.strip())
    got = [int(txt["sel%d" % i]) for i in range(4)]
    want = [0, 2, 0, 2]         # 처음 0, 오른쪽(1 번은 죽었다) 2, 감겨서 0, 왼쪽 2
    ay = int(txt["arrowy"])
    xs = [arrow_x(os.path.join(outdir, "pick%d.bin" % i), ay) for i in range(3)]
    # 칸 폭 32, 화살표는 칸 가운데 -> 칸 c 의 x = VIEW_X + c*32 + (32-12)/2
    wantx = [VIEW_X + c * 32 + (32 - ARROW_W) // 2 for c in (0, 2)] + [None]
    hit = int(txt["hit"])
    hp0, hp2 = int(txt["hp0"]), int(txt["hp2"])
    ok_move = got == want
    ok_draw = xs == wantx
    # 맞았으면 2 번만 깎인다. 빗나가면 아무도 안 깎이지만 고른 칸은 그대로다.
    ok_hit = hit == 2 and hp0 == BIG_HP and hp2 <= BIG_HP
    print("pick   커서 %s (바란 것 %s)  %s" % (got, want, "OK" if ok_move else "FAIL"))
    print("       화살표 x %s (바란 것 %s)  %s" % (xs, wantx, "OK" if ok_draw else "FAIL"))
    print("       친 칸 %d, 0 번 HP %d, 2 번 HP %d  %s"
          % (hit, hp0, hp2, "OK" if ok_hit else "FAIL"))
    if not (ok_move and ok_draw and ok_hit):
        bad += 1

    # ---- 라운드 도중에 쓰러지면 --------------------------------------------
    txt = dict(l.split(None, 1) for l in
               io.open(os.path.join(outdir, "die.txt")).read().split("\n") if l.strip())
    base = view(os.path.join(outdir, "die_base.bin"))
    before = cell_diff(base, view(os.path.join(outdir, "die_before.bin")), 2)
    after = cell_diff(base, view(os.path.join(outdir, "die_after.bin")), 2)
    hp0, hp1 = int(txt["hp0"]), int(txt["hp1"])
    ok_die = (hp0 == 0 and hp1 > 0
              and before[0] >= MIN_PIX and before[1] >= MIN_PIX
              and after[0] == 0 and after[1] >= MIN_PIX)
    print("die    쓰러지기 전 %s -> 뒤 %s   0 번 HP %d, 1 번 HP %d  %s"
          % (before, after, hp0, hp1, "OK" if ok_die else "FAIL"))
    if not ok_die:
        bad += 1
        print("       바란 것: 두 칸 다 차 있다가 0 번만 비고, 0 번은 HP 0")
    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    if sys.argv[1] == "tcl":
        write_tcl(sys.argv[2])
    else:
        sys.exit(check(sys.argv[2]))
