"""대열을 확인한다 - 무리를 여러 마리로 세우고 칠 상대를 고르는 것.

SCREEN 8 에는 픽셀 단위 오라클(verify_quest_sides)이 없다. 그래서 여기서는
**던전만 그린 화면과 대열을 얹은 화면의 차이**를 오라클로 쓴다. 칸마다 달라진
픽셀을 세면 그 자리에 몬스터가 섰는지 아닌지가 나온다. 그림이 무엇이든,
어떻게 줄었든 상관없이 "n 마리가 제 칸에 있다" 만 본다.

  layout  n = 1..4 일 때 칸 폭이 VIEW_W/n 이고 n 개 칸에만 몬스터가 있다
  dead    쓰러진 칸은 비고 나머지는 그대로다 (칸을 당겨오지 않는다)
  pick    화살표가 좌우로 돌고, 쓰러진 칸은 건너뛰고, 고른 칸이 실제로 맞는다
  die     라운드 **도중에** 쓰러지면 그 칸이 저절로 빈다 (MonDiedRedraw)
  left    화살표가 지나간 자리에 아무것도 안 남는다
  updown  두 줄일 때 위아래로도 고를 수 있다 (다섯 마리 = 3 칸 x 2 줄)
  mix     섞인 무리는 칸마다 다른 그림이 선다

pick 이 고른 칸을 어떻게 확인하는가: HeroAttack 이 PickTarget 의 결과를 바로
TmpType 에 넣는다. 굴리기 **전**이라 빗나가도 남으므로, 굴림에 기대지 않고
확인할 수 있다. 다만 **DoAttack 에 들어가는 순간에 읽어야 한다.** MonAttack 도
같은 자리를 자기 번호로 덮으므로, 라운드가 끝난 뒤에 읽으면 마지막으로 친
몬스터의 번호가 나온다(실제로 그랬다).

  uv run python gfx/quest_row.py tcl   <작업폴더>
  uv run python gfx/quest_row.py check <작업폴더>
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SYM = os.path.join(HERE, "..", "build", "quest3.sym")

sys.path.insert(0, HERE)
import quest_geom as G                                      # noqa: E402

VIEW_X, VIEW_Y, VIEW_W, VIEW_H = 16, 8, 96, 96
MON_N, MON_STRIDE = 5, 4
PARTY_N, PARTY_STRIDE = 6, 32
P_DEX, P_HP, P_MAXHP, P_ATK, P_DCNT, P_DSIDE, P_DMOD = 15, 21, 22, 24, 25, 26, 27
ARROW_COL = 0xFC
ARROW_W = 12
BIG_HP = 200

# 한 칸에 몬스터가 있다고 볼 최소 픽셀 수. 가장 작은 24x24 칸도 실측 300 픽셀
# 넘게 바뀌므로 넉넉하다. 빈 칸은 0 이다.
MIN_PIX = 100


def syms():
    out = {}
    for line in io.open(SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            out[name] = int(val.strip(), 16)
    return out


def setup(S, kind, alive, hp=BIG_HP):
    """파티와 무리를 원하는 꼴로 앉힌다. alive = 살아 있는 칸의 목록."""
    w = []
    for i in range(PARTY_N):
        b = S["Party"] + i * PARTY_STRIDE
        w += ["debug write memory %d 255" % (b + P_HP),
              "debug write memory %d 255" % (b + P_MAXHP),
              "debug write memory %d 10" % (b + P_DEX),
              "debug write memory %d 40" % (b + P_ATK),    # 거의 늘 맞게
              "debug write memory %d 1" % (b + P_DCNT),
              "debug write memory %d 6" % (b + P_DSIDE),
              "debug write memory %d 0" % (b + P_DMOD)]
    for i in range(MON_N):
        b = S["Monsters"] + i * MON_STRIDE
        v = hp if i in alive else 0
        w += ["debug write memory %d %d" % (b + 0, kind),
              "debug write memory %d %d" % (b + 1, v),
              "debug write memory %d %d" % (b + 2, v)]
    return w


def dumpview(path):
    """던전 창 96 줄을 통째로 뜬다. 한 줄이 256 바이트다."""
    return ['set f [open "%s" wb]' % path,
            "fconfigure $f -translation binary",
            "puts -nonewline $f [debug read_block VRAM %d %d]"
            % (VIEW_Y * 256, VIEW_H * 256),
            "close $f"]


def key(t, mask):
    return ["after time %.2f { keymatrixdown 8 %s }" % (t, mask),
            "after time %.2f { keymatrixup   8 %s }" % (t + 0.15, mask)]


KEY_SPACE, KEY_RIGHT, KEY_LEFT = "0x01", "0x80", "0x10"
KEY_UP, KEY_DOWN = "0x20", "0x40"

# (이름, 종류, 마릿수, 살아 있는 칸)
LAYOUT = [("n1", 0, 1, [0]),
          ("n2", 0, 2, [0, 1]),
          ("n3", 4, 3, [0, 1, 2]),
          ("n4", 2, 4, [0, 1, 2, 3]),
          ("n5", 0, 5, [0, 1, 2, 3, 4]),   # 3 칸 x 2 줄
          ("dead", 0, 3, [0, 2])]     # 가운데가 쓰러진 채로


def write_tcl(outdir):
    S = syms()
    out = outdir.replace(chr(92), "/")

    for name, kind, count, alive in LAYOUT:
        L = ["# %s - generated by gfx/quest_row.py" % name,
             # 먼저 전투 없이 던전만 그린다 (견줄 바탕).
             "after time 6 { debug write memory %d 0 ; debug write memory %d 1 }"
             % (S["BattleOn"], S["needDraw"]),
             "after time 7.5 { %s }" % " ; ".join(dumpview("%s/%s_base.bin" % (out, name))),
             "after time 8 { %s ; debug write memory %d %d ; "
             "debug write memory %d %d ; debug write memory %d 1 ; "
             "debug write memory %d 1 }"
             % (" ; ".join(setup(S, kind, alive)), S["MonCount"], count,
                S["MonKind"], kind, S["BattleOn"], S["needDraw"]),
             "after time 9.5 {",
             "  " + "\n  ".join(dumpview("%s/%s_row.bin" % (out, name))),
             '  set g [open "%s/%s.txt" w]' % (out, name),
             '  puts $g "roww [debug read memory %d]"' % S["MonRowW"],
             '  puts $g "rown [debug read memory %d]"' % S["MonRowN"],
             "  close $g ; exit",
             "}"]
        io.open(os.path.join(outdir, name + ".tcl"), "w",
                encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 화살표 -----------------------------------------------------------
    # 가운데(1 번)가 쓰러진 셋. 오른쪽을 누르면 1 번을 건너뛰고 2 번으로 가야
    # 한다. 한 번 더 누르면 0 번으로 감기고, 왼쪽을 누르면 다시 2 번이다.
    L = ["# pick - generated by gfx/quest_row.py",
         'set ::fh [open "%s/pick.txt" w]' % out,
         "after time 6 { %s ; debug write memory %d 3 ; "
         "debug write memory %d 0 ; debug write memory %d 1 ; "
         "debug write memory %d 1 ; debug write memory %d 1 }"
         % (" ; ".join(setup(S, 0, [0, 2])), S["MonCount"], S["MonKind"],
            S["BattleOn"], S["RoundNo"], S["needDraw"])]
    L += key(7.0, KEY_SPACE)                # 라운드 시작
    L += key(8.0, KEY_SPACE)                # 명령 = ATTACK -> PickTarget
    L += ['after time 9.0 { puts $::fh "sel0 [debug read memory %d]" ; '
          'puts $::fh "arrowy [debug read memory %d]" ; '
          '%s }' % (S["MonSel"], S["ArrowY"],
                    " ; ".join(dumpview("%s/pick0.bin" % out)))]
    L += key(9.5, KEY_RIGHT)
    L += ['after time 10.5 { puts $::fh "sel1 [debug read memory %d]" ; '
          '%s }' % (S["MonSel"], " ; ".join(dumpview("%s/pick1.bin" % out)))]
    L += key(11.0, KEY_RIGHT)               # 끝을 넘어 0 번으로 감긴다
    L += ['after time 12.0 { puts $::fh "sel2 [debug read memory %d]" }' % S["MonSel"]]
    L += key(12.5, KEY_LEFT)                # 왼쪽으로 감겨 다시 2 번
    L += ['after time 13.5 { puts $::fh "sel3 [debug read memory %d]" }' % S["MonSel"]]
    # 결정한 뒤 첫 DoAttack 이 이 사람의 공격이다. 그 자리에서 TmpType 을 읽는다.
    L += ["set ::armed 0",
          "debug set_bp %d 1 { if {$::armed} { set ::armed 0 ; "
          'puts $::fh "hit [debug read memory %d]" } }'
          % (S["DoAttack"], S["TmpType"]),
          "after time 13.8 { set ::armed 1 }"]
    L += key(14.0, KEY_SPACE)               # 결정
    L += ['after time 15.5 {',
          '  puts $::fh "hp0 [debug read memory %d]"' % (S["Monsters"] + 1),
          '  puts $::fh "hp2 [debug read memory %d]"'
          % (S["Monsters"] + 2 * MON_STRIDE + 1),
          "  " + "\n  ".join(dumpview("%s/pick2.bin" % out)),
          "  close $::fh ; exit",
          "}"]
    io.open(os.path.join(outdir, "pick.tcl"), "w",
            encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 라운드 도중에 쓰러지면 --------------------------------------------
    #
    # 0 번의 HP 를 1 로 두면 첫 공격에 쓰러진다 (기본 표적이 FirstMonster 라
    # 0 번이다). 그 뒤로 **needDraw 를 건드리지 않는데도** 0 번 칸이 비어야
    # 한다. 그 일을 하는 것이 MonDiedRedraw 다 - 쓰러진 자리를 지우려면 뒤의
    # 던전 그림이 있어야 하는데 우리에게 없으니 던전부터 다시 그린다.
    #
    # 스페이스를 여러 번 눌러 여러 사람이 친다. 자연 1 은 무조건 빗나가므로
    # 한 번만 치면 스무 번에 한 번 실패하는 검사가 된다.
    L = ["# die - generated by gfx/quest_row.py",
         "after time 6 { debug write memory %d 0 ; debug write memory %d 1 }"
         % (S["BattleOn"], S["needDraw"]),
         "after time 7.0 { %s }" % " ; ".join(dumpview("%s/die_base.bin" % out)),
         "after time 7.5 { %s ; debug write memory %d 1 ; "
         "debug write memory %d 2 ; debug write memory %d 0 ; "
         "debug write memory %d 1 ; debug write memory %d 1 }"
         % (" ; ".join(setup(S, 0, [0, 1])), S["Monsters"] + 1,
            S["MonCount"], S["MonKind"], S["BattleOn"], S["RoundNo"]),
         "after time 8.0 { debug write memory %d 1 }" % S["needDraw"],
         "after time 9.0 { %s }" % " ; ".join(dumpview("%s/die_before.bin" % out))]
    t = 9.5
    while t < 15.0:                         # 스페이스를 계속 누른다
        L += key(t, KEY_SPACE)
        t += 0.6
    L += ["after time 16.0 {",
          "  " + "\n  ".join(dumpview("%s/die_after.bin" % out)),
          '  set g [open "%s/die.txt" w]' % out,
          '  puts $g "hp0 [debug read memory %d]"' % (S["Monsters"] + 1),
          '  puts $g "hp1 [debug read memory %d]"'
          % (S["Monsters"] + MON_STRIDE + 1),
          "  close $g ; exit",
          "}"]
    io.open(os.path.join(outdir, "die.tcl"), "w",
            encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 화살표가 지나간 자리 ----------------------------------------------
    #
    # 아무도 안 죽는 무리(HP 200)를 세워 두고,
    #
    #   A0 = 화살표를 띄우기 **전**의 창
    #   A1 = 고르고 나서 굴리기 직전(DoAttack 입구)의 창
    #
    # 을 견준다. 그 사이에 바뀐 것은 화살표를 띄웠다 지운 것뿐이므로 **둘은
    # 픽셀까지 같아야 한다.** 다르면 화살표 자리가 안 지워진 것이다.
    #
    # 실제로 벽 한가운데에 12x6 짜리 조각이 남은 화면이 나왔다. 그 크기가 곧
    # ARROW_W x ARROW_H 라 여기서 잡힌다.
    #
    # 창을 다시 그려서 견주지 않는 이유: 이때 메인 루프는 BattleRound 안에서
    # 멈춰 있어 needDraw 가 안 먹는다.
    L = ["# left - generated by gfx/quest_row.py",
         "after time 6 { %s ; debug write memory %d 3 ; "
         "debug write memory %d 0 ; debug write memory %d 1 ; "
         "debug write memory %d 1 ; debug write memory %d 1 }"
         % (" ; ".join(setup(S, 0, [0, 1, 2])), S["MonCount"], S["MonKind"],
            S["BattleOn"], S["RoundNo"], S["needDraw"]),
         "after time 8.0 { %s }" % " ; ".join(dumpview("%s/left_a0.bin" % out)),
         "set ::armed 0",
         "debug set_bp %d 1 { if {$::armed} { set ::armed 0 ; %s } }"
         % (S["DoAttack"], " ; ".join(dumpview("%s/left_a1.bin" % out)))]
    L += key(9.0, KEY_SPACE)                # 라운드 시작
    L += key(10.0, KEY_SPACE)               # 명령 = ATTACK -> 화살표
    L += key(11.0, KEY_RIGHT)               # 한 칸 옮긴다
    L += key(12.0, KEY_RIGHT)               # 또 한 칸
    L += ["after time 12.8 { set ::armed 1 }"]
    L += key(13.0, KEY_SPACE)               # 결정 -> 지우고 굴린다
    # verify_quest_row.ps1 이 스크립트마다 .txt 가 나오기를 기다린다.
    L += ['after time 15.0 { set g [open "%s/left.txt" w] ; '
          'puts $g "sel [debug read memory %d]" ; close $g ; exit }'
          % (out, S["MonSel"])]
    io.open(os.path.join(outdir, "left.tcl"), "w",
            encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 두 줄일 때 위아래로 고르기 ----------------------------------------
    #
    # 다섯 마리는 3 칸 x 2 줄이다. 0 번(윗줄 왼쪽)에서 아래를 누르면 3 번,
    # 한 번 더 누르면 6 -> 감겨서 1 번, 위를 누르면 -2 -> 감겨서 3 번이다.
    # 화살표의 줄(ArrowY)도 함께 본다 - 칸만 옮기고 화살표가 안 따라가면
    # 화면으로는 못 고른다.
    L = ["# updown - generated by gfx/quest_row.py",
         'set ::fh [open "%s/updown.txt" w]' % out,
         "after time 6 { %s ; debug write memory %d 5 ; "
         "debug write memory %d 0 ; debug write memory %d 1 ; "
         "debug write memory %d 1 ; debug write memory %d 1 }"
         % (" ; ".join(setup(S, 0, [0, 1, 2, 3, 4])), S["MonCount"], S["MonKind"],
            S["BattleOn"], S["RoundNo"], S["needDraw"])]
    L += key(7.0, KEY_SPACE)                # 라운드 시작
    L += key(8.0, KEY_SPACE)                # 명령 = ATTACK -> 화살표
    t = 9.0
    for i, k in enumerate(("", KEY_DOWN, KEY_DOWN, KEY_UP)):
        if k:
            L += key(t, k)
            t += 1.0
        L += ['after time %.2f { puts $::fh "sel%d [debug read memory %d] '
              '[debug read memory %d]" }' % (t, i, S["MonSel"], S["ArrowY"])]
        t += 0.5
    L += ['after time %.2f { %s ; close $::fh ; exit }'
          % (t, " ; ".join(dumpview("%s/updown.bin" % out)))]
    io.open(os.path.join(outdir, "updown.tcl"), "w",
            encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 섞인 무리 ---------------------------------------------------------
    #
    # 두 가지를 본다.
    #
    #   그림  칸마다 M_TYPE 이 다르면 그림도 달라야 한다. 같은 종류 둘이면
    #         두 칸의 픽셀이 **똑같다**(같은 그림, 같은 크기). 그것을 대조군으로
    #         쓰면 "정말 다른 그림인가" 를 그림 내용을 몰라도 말할 수 있다.
    #   AC    1 번 칸을 칠 때 TgtAc 가 **1 번의** 종류에서 나와야 한다. 예전에는
    #         무리 전체의 MonKind 에서 읽어서, 섞이면 엉뚱한 AC 로 판정했다.
    #
    # TROLL(AC 15) 과 SLIME(AC 8) 을 쓴다. 값이 멀어 헷갈릴 일이 없다.
    for name, t0, t1 in (("mixsame", 0, 0), ("mixdiff", 3, 1)):
        w = []
        for i in range(PARTY_N):
            b = S["Party"] + i * PARTY_STRIDE
            w += ["debug write memory %d 255" % (b + P_HP),
                  "debug write memory %d 255" % (b + P_MAXHP),
                  "debug write memory %d 10" % (b + P_DEX),
                  "debug write memory %d 40" % (b + P_ATK),
                  "debug write memory %d 1" % (b + P_DCNT),
                  "debug write memory %d 6" % (b + P_DSIDE),
                  "debug write memory %d 0" % (b + P_DMOD)]
        for i in range(MON_N):
            b = S["Monsters"] + i * MON_STRIDE
            v = BIG_HP if i < 2 else 0
            w += ["debug write memory %d %d" % (b + 0, (t0, t1)[i] if i < 2 else t0),
                  "debug write memory %d %d" % (b + 1, v),
                  "debug write memory %d %d" % (b + 2, v)]
        w += ["debug write memory %d 2" % S["MonCount"],
              "debug write memory %d %d" % (S["MonKind"], t0),
              "debug write memory %d %d" % (S["MonKind2"], t1),
              "debug write memory %d 1" % S["BattleOn"],
              "debug write memory %d 1" % S["RoundNo"],
              "debug write memory %d 1" % S["needDraw"]]
        L = ["# %s - generated by gfx/quest_row.py" % name,
             'set ::fh [open "%s/%s.txt" w]' % (out, name),
             # 먼저 몬스터 없이 던전만 (바탕). 그림은 투명한 곳이 있어서 뒤의
             # 던전이 비쳐 보이므로, 바탕을 빼야 "그림이 같은가" 를 볼 수 있다.
             "after time 6.0 { debug write memory %d 0 ; debug write memory %d 1 }"
             % (S["BattleOn"], S["needDraw"]),
             "after time 7.0 { %s }" % " ; ".join(dumpview("%s/%s_base.bin" % (out, name))),
             "after time 7.5 { %s }" % " ; ".join(w),
             "after time 8.5 { %s }" % " ; ".join(dumpview("%s/%s.bin" % (out, name))),
             "set ::armed 0",
             "debug set_bp %d 1 { if {$::armed} { set ::armed 0 ; "
             'puts $::fh "tgtac [debug read memory %d]" ; '
             'puts $::fh "hit [debug read memory %d]" } }'
             % (S["DoAttack"], S["TgtAc"], S["TmpType"])]
        L += key(9.5, KEY_SPACE)            # 라운드 시작
        L += key(10.0, KEY_SPACE)           # 명령 = ATTACK -> 화살표
        L += key(11.0, KEY_RIGHT)           # 1 번 칸으로
        L += ["after time 11.8 { set ::armed 1 }"]
        L += key(12.0, KEY_SPACE)           # 결정
        L += ['after time 14.0 { close $::fh ; exit }']
        io.open(os.path.join(outdir, name + ".tcl"), "w",
                encoding="ascii", newline="\n").write("\n".join(L) + "\n")

    # ---- 층이 깊으면 두 종류가 섞인다 --------------------------------------
    #
    # 전투 밖에서 스페이스를 누르면 StartBattle 이 돈다. 누를 때마다 BattleOn 을
    # 0 으로 되돌려 무리를 여러 번 새로 만들고, MonKind 와 MonKind2 가 갈리는
    # 횟수를 센다. 1 층은 한 번도 갈리면 안 되고, 2 층은 세 번에 한 번꼴이라
    # 스무 번이면 거의 확실히 갈린다((2/3)^20 = 0.03%).
    for name, floor in (("floor1", 1), ("floor2", 2)):
        L = ["# %s - generated by gfx/quest_row.py" % name,
             'set ::fh [open "%s/%s.txt" w]' % (out, name),
             "after time 6 { debug write memory %d %d ; debug write memory %d 0 }"
             % (S["DungeonFloor"], floor, S["BattleOn"])]
        t = 6.5
        for i in range(20):
            L += key(t, KEY_SPACE)
            L += ['after time %.2f { puts $::fh "roll [debug read memory %d] '
                  '[debug read memory %d] [debug read memory %d]" ; '
                  'debug write memory %d 0 }'
                  % (t + 0.4, S["MonKind"], S["MonKind2"], S["MonCount"],
                     S["BattleOn"])]
            t += 0.7
        L += ["after time %.2f { close $::fh ; exit }" % (t + 0.5)]
        io.open(os.path.join(outdir, name + ".tcl"), "w",
                encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote %d tcl scripts" % (len(LAYOUT) + 8))


# --------------------------------------------------------------------------


def view(path):
    """뜬 VRAM 에서 던전 창만 잘라 낸다. [y][x] 로 본다."""
    b = io.open(path, "rb").read()
    return [b[r * 256 + VIEW_X:r * 256 + VIEW_X + VIEW_W] for r in range(VIEW_H)]


def cell_diff(base, row, count):
    """칸마다 바탕과 달라진 픽셀 수.

    배치(칸 수 / 줄 수 / 폭 / 줄 자리)는 gfx/quest_geom.py 의 mon_layout 이
    정본이다. 여기서 따로 계산하면 롬과 검사가 같이 틀려도 통과한다.
    """
    cols, rows, w, top, step = G.mon_layout(count)
    out = []
    for i in range(count):
        cx, cy = (i % cols) * w, top - VIEW_Y + (i // cols) * step
        n = 0
        for y in range(cy, cy + w):
            for x in range(cx, cx + w):
                if base[y][x] != row[y][x]:
                    n += 1
        out.append(n)
    return out


def arrow_x(path, ay):
    """ArrowY 줄의 화살표 왼쪽 끝. 없으면 None.

    **줄을 롬이 알려 준 ArrowY 로 못 박는다.** 아무 줄에서나 노란 픽셀 열두 개를
    찾으면, 나중에 몬스터 그림에 그만한 노란 줄이 생겼을 때 엉뚱한 줄을 읽고도
    조용히 통과한다.
    """
    v = view(path)
    y = ay - VIEW_Y
    xs = [x for x in range(VIEW_W) if v[y][x] == ARROW_COL]
    return min(xs) + VIEW_X if len(xs) == ARROW_W else None


def check(outdir):
    bad = 0
    for name, _kind, count, alive in LAYOUT:
        txt = dict(l.split(None, 1) for l in
                   io.open(os.path.join(outdir, name + ".txt")).read().split("\n") if l.strip())
        roww, rown = int(txt["roww"]), int(txt["rown"])
        base = view(os.path.join(outdir, name + "_base.bin"))
        row = view(os.path.join(outdir, name + "_row.bin"))
        diff = cell_diff(base, row, count)
        cols, rows, want_w, _t, _s = G.mon_layout(count)
        ok = (roww == want_w and rown == count
              and all((d >= MIN_PIX) == (i in alive) for i, d in enumerate(diff)))
        print("%-6s %d 마리 = %d 칸 x %d 줄, 폭 %2d   칸별 바뀐 픽셀 %s   %s"
              % (name, count, cols, rows, roww, diff, "OK" if ok else "FAIL"))
        if not ok:
            bad += 1
            print("       바란 것: 폭 %d, 칸 수 %d, 몬스터가 선 칸 %s"
                  % (want_w, count, alive))

    txt = dict(l.split(None, 1) for l in
               io.open(os.path.join(outdir, "pick.txt")).read().split("\n") if l.strip())
    got = [int(txt["sel%d" % i]) for i in range(4)]
    want = [0, 2, 0, 2]         # 처음 0, 오른쪽(1 번은 죽었다) 2, 감겨서 0, 왼쪽 2
    ay = int(txt["arrowy"])
    xs = [arrow_x(os.path.join(outdir, "pick%d.bin" % i), ay) for i in range(3)]
    cols, _r, w, _t, _s = G.mon_layout(3)
    wantx = [VIEW_X + c * w + (w - ARROW_W) // 2 for c in (0, 2)] + [None]
    hit = int(txt["hit"])
    hp0, hp2 = int(txt["hp0"]), int(txt["hp2"])
    ok_move = got == want
    ok_draw = xs == wantx
    # 맞았으면 2 번만 깎인다. 빗나가면 아무도 안 깎이지만 고른 칸은 그대로다.
    ok_hit = hit == 2 and hp0 == BIG_HP and hp2 <= BIG_HP
    print("pick   커서 %s (바란 것 %s)  %s" % (got, want, "OK" if ok_move else "FAIL"))
    print("       화살표 x %s (바란 것 %s)  %s" % (xs, wantx, "OK" if ok_draw else "FAIL"))
    print("       친 칸 %d, 0 번 HP %d, 2 번 HP %d  %s"
          % (hit, hp0, hp2, "OK" if ok_hit else "FAIL"))
    if not (ok_move and ok_draw and ok_hit):
        bad += 1

    # ---- 라운드 도중에 쓰러지면 --------------------------------------------
    txt = dict(l.split(None, 1) for l in
               io.open(os.path.join(outdir, "die.txt")).read().split("\n") if l.strip())
    base = view(os.path.join(outdir, "die_base.bin"))
    before = cell_diff(base, view(os.path.join(outdir, "die_before.bin")), 2)
    after = cell_diff(base, view(os.path.join(outdir, "die_after.bin")), 2)
    hp0, hp1 = int(txt["hp0"]), int(txt["hp1"])
    ok_die = (hp0 == 0 and hp1 > 0
              and before[0] >= MIN_PIX and before[1] >= MIN_PIX
              and after[0] == 0 and after[1] >= MIN_PIX)
    print("die    쓰러지기 전 %s -> 뒤 %s   0 번 HP %d, 1 번 HP %d  %s"
          % (before, after, hp0, hp1, "OK" if ok_die else "FAIL"))
    if not ok_die:
        bad += 1
        print("       바란 것: 두 칸 다 차 있다가 0 번만 비고, 0 번은 HP 0")

    # ---- 화살표가 지나간 자리 ----------------------------------------------
    a0 = view(os.path.join(outdir, "left_a0.bin"))
    a1 = view(os.path.join(outdir, "left_a1.bin"))
    diff = [(x, y) for y in range(VIEW_H) for x in range(VIEW_W)
            if a0[y][x] != a1[y][x]]
    print("left   화살표 전후로 다른 픽셀 %d 개  %s"
          % (len(diff), "OK" if not diff else "FAIL"))
    if diff:
        bad += 1
        xs = [d[0] for d in diff]
        ys = [d[1] for d in diff]
        print("       창 안 x %d..%d, y %d..%d (폭 %d, 높이 %d) "
              "- ARROW_W x ARROW_H 는 %d x %d"
              % (min(xs), max(xs), min(ys), max(ys),
                 max(xs) - min(xs) + 1, max(ys) - min(ys) + 1, 12, 6))


    # ---- 두 줄일 때 위아래로 고르기 ----------------------------------------
    txt = dict((l.split(None, 1)[0], l.split(None, 1)[1]) for l in
               io.open(os.path.join(outdir, "updown.txt")).read().split("\n") if l.strip())
    got = [tuple(int(v) for v in txt["sel%d" % i].split()) for i in range(4)]
    cols, rows, w, top, step = G.mon_layout(5)
    band = G.ARROW_H + G.ARROW_GAP
    ay = [top + r * step - band for r in range(rows)]
    want = [(0, ay[0]), (3, ay[1]), (1, ay[0]), (3, ay[1])]
    ok_ud = got == want
    print("updown 칸/화살표줄 %s" % (got,))
    print("       바란 것     %s  %s" % (want, "OK" if ok_ud else "FAIL"))
    if not ok_ud:
        bad += 1

    # ---- 섞인 무리 ---------------------------------------------------------
    def cell_mark(base, v, i, count):
        """칸 안에서 바탕과 달라진 픽셀을 (칸 안 좌표, 색) 로 모은다.

        그림은 투명한 곳을 아예 안 그려서 뒤의 던전이 비쳐 보인다. 그래서 같은
        그림이라도 놓인 자리가 다르면 픽셀이 다르다. 바탕을 빼면 그림 자체만
        남으므로, 두 칸이 같은 그림인지 그림 내용을 몰라도 말할 수 있다.
        """
        c, _r, cw, tp, st = G.mon_layout(count)
        cx, cy = (i % c) * cw, tp - VIEW_Y + (i // c) * st
        return set((x - cx, y - cy, v[y][x]) for y in range(cy, cy + cw)
                   for x in range(cx, cx + cw) if base[y][x] != v[y][x])

    for name, same in (("mixsame", True), ("mixdiff", False)):
        base = view(os.path.join(outdir, name + "_base.bin"))
        v = view(os.path.join(outdir, name + ".bin"))
        a, b = cell_mark(base, v, 0, 2), cell_mark(base, v, 1, 2)
        # 딱 같기를 바라면 안 된다. 그림 색이 우연히 뒤의 벽과 같은 픽셀은
        # "안 바뀐 것" 으로 잡혀서, 같은 그림 둘이 한 점 어긋난다(실측 601/602).
        # 겹치는 비율로 본다 - 같은 그림은 99%, 다른 그림은 5% 였다.
        share = len(a & b) / float(max(len(a), len(b), 1))
        eq = share > 0.9
        txt = dict(l.split(None, 1) for l in
                   io.open(os.path.join(outdir, name + ".txt")).read().split("\n") if l.strip())
        ac, hit = int(txt["tgtac"]), int(txt["hit"])
        want_ac = 15 if same else 8         # TROLL 15, SLIME 8
        ok = (eq == same) and hit == 1 and ac == want_ac
        print("%-7s 두 칸의 그림이 %s (겹침 %.0f%%)   1 번을 칠 때 TgtAc %d "
              "(바란 것 %d)  %s"
              % (name, "같다" if eq else "다르다", share * 100, ac, want_ac,
                 "OK" if ok else "FAIL"))
        if not ok:
            bad += 1

    # ---- 층이 깊으면 두 종류가 섞인다 --------------------------------------
    for name, floor, want_mixed in (("floor1", 1, False), ("floor2", 2, True)):
        rolls = [l.split()[1:] for l in
                 io.open(os.path.join(outdir, name + ".txt")).read().split("\n")
                 if l.startswith("roll")]
        mixed = sum(1 for r in rolls if r[0] != r[1])
        ok = (mixed > 0) == want_mixed
        print("%-7s %d 번 만든 무리 중 섞인 것 %d 개  %s"
              % (name, len(rolls), mixed, "OK" if ok else "FAIL"))
        if not ok:
            bad += 1
            print("       %d 층은 %s"
                  % (floor, "섞이면 안 된다" if not want_mixed else "가끔 섞여야 한다"))

    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    if sys.argv[1] == "tcl":
        write_tcl(sys.argv[2])
    else:
        sys.exit(check(sys.argv[2]))
