"""민첩이 정하는 전투 행동 횟수를 확인한다 (quest_sena.md 의 전투방식).

  행동 횟수 = floor(내 민첩 / 이 전장의 최저 민첩)

한 라운드는 여러 바퀴로 돈다. 첫 바퀴에는 모두, 둘째 바퀴에는 두 번 이상 움직일
것만, ... 아무도 못 움직이는 바퀴가 나오면 라운드 끝. 바퀴 안에서는 예전처럼
우리 편 하나 / 상대 하나로 번갈아 간다.

민첩을 정해 놓고 한 라운드를 돌린 뒤, **누가 몇 번째로 쳤는지 순서 전체**를
HeroAttack / MonAttack 브레이크포인트로 받아 적어 파이썬 모델과 대조한다.

두 가지를 알고 맞춰 두었다.

  - 몬스터 민첩은 MonsterTable 에 있고 그건 **롬**이라 debug write 로 못 바꾼다.
    그래서 종류를 골라 쓰고, 그 종류의 민첩은 빌드된 롬에서 직접 읽어 온다.
  - 브레이크포인트는 루틴 **입구**에서 걸리므로 죽은 몬스터의 호출도 잡힌다
    (MonAttack 이 안에서 바로 돌아간다). 모델도 그렇게 센다.

  uv run python gfx/quest_turns.py tcl   <작업폴더>
  uv run python gfx/quest_turns.py check <작업폴더>
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SYM = os.path.join(HERE, "..", "build", "quest.sym")
ROM = os.path.join(HERE, "..", "build", "quest.rom")
PARTY_N, MON_N = 6, 5
MON_TSTRIDE, T_DEX = 21, 6
BIG_HP = 255

# 파티 기록 오프셋 (questrules.asm 과 같아야 한다)
P_DEX, P_HP, P_MAXHP, P_AC, P_ATK, P_DCNT, P_DSIDE, P_DMOD = 15, 21, 22, 23, 24, 25, 26, 27
PARTY_STRIDE, MON_STRIDE = 32, 4

# (사람 여섯의 민첩, 몬스터 종류, 살아 있는 마릿수)
CASES = {
    "even":    ([10, 10, 10, 10, 10, 10], 2, 3),   # 모두 비슷하면 모두 한 번씩
    "split":   ([15, 5, 10, 12, 5, 9], 1, 2),      # 최저 5 - 15 인 사람은 세 번
    "slowmon": ([18, 17, 16, 15, 14, 13], 1, 2),   # 몬스터가 제일 굼뜨다
    "fastmon": ([6, 6, 7, 6, 8, 6], 4, 4),         # 몬스터가 제일 빠르다
    "zero":    ([0, 6, 6, 6, 6, 6], 1, 1),         # 민첩 0 - 0 으로 나누면 안 된다
}


def syms():
    out = {}
    for line in open(SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            out[name] = int(val.strip(), 16)
    return out


def mon_dex(S, kind):
    """빌드된 롬에서 그 종류의 민첩을 읽는다. 본체는 0x4000 에 놓인다."""
    rom = open(ROM, "rb").read()
    return rom[S["MonsterTable"] - 0x4000 + kind * MON_TSTRIDE + T_DEX]


def model(dexes, mondex, nmon):
    alive = list(dexes) + [mondex] * nmon
    dmin = max(1, min(alive))
    acts = [max(1, d // dmin) for d in dexes]
    amon = max(1, mondex // dmin)
    seq, p = [], 1
    while True:
        acted = False
        for i in range(max(PARTY_N, MON_N)):
            if i < PARTY_N and acts[i] >= p:
                seq.append("H%d" % i)
                acted = True
            if i < MON_N and amon >= p:       # 죽은 몬스터도 호출은 된다
                seq.append("M%d" % i)
                acted = True
        if not acted:
            break
        p += 1
    return dmin, acts, amon, seq


def write_tcl(outdir):
    S = syms()
    for name, (dexes, kind, nmon) in CASES.items():
        w = []
        for i, d in enumerate(dexes):
            b = S["Party"] + i * PARTY_STRIDE
            w += ["debug write memory %d %d" % (b + P_DEX, d),
                  "debug write memory %d %d" % (b + P_HP, BIG_HP),
                  "debug write memory %d %d" % (b + P_MAXHP, BIG_HP),
                  "debug write memory %d 30" % (b + P_AC),      # 거의 안 맞게
                  "debug write memory %d 0" % (b + P_ATK),
                  "debug write memory %d 1" % (b + P_DCNT),     # 피해 1 - 아무도
                  "debug write memory %d 1" % (b + P_DSIDE),    # 안 죽어야 순서만
                  "debug write memory %d 0" % (b + P_DMOD)]     # 남는다
        for i in range(MON_N):
            b = S["Monsters"] + i * MON_STRIDE
            hp = BIG_HP if i < nmon else 0
            w += ["debug write memory %d %d" % (b + 1, hp),
                  "debug write memory %d %d" % (b + 2, hp)]
        w += ["debug write memory %d %d" % (S["MonCount"], nmon),
              "debug write memory %d %d" % (S["MonKind"], kind),
              "debug write memory %d 1" % S["BattleOn"],
              "debug write memory %d 1" % S["RoundNo"]]
        out = os.path.join(outdir, name + ".txt").replace("\\", "/")
        L = ["# %s - generated by gfx/quest_turns.py" % name,
             'set ::fh [open "%s" w]' % out,
             "set ::seq {}",
             "set ::go 0",
             "after time 7 { %s ; set ::go 1 }" % " ; ".join(w),
             "debug set_bp %d 1 { if {$::go == 2} { lappend ::seq H[reg a] } }"
             % S["HeroAttack"],
             "debug set_bp %d 1 { if {$::go == 2} { lappend ::seq M[reg a] } }"
             % S["MonAttack"],
             "debug set_bp %d 1 {" % S["MainLoop"],
             "  if {$::go != 1} { return }",
             "  set ::go 2",
             "  set sp [expr [reg sp] - 2]",
             "  debug write memory $sp %d" % (S["MainLoop"] & 0xFF),
             "  debug write memory [expr $sp + 1] %d" % (S["MainLoop"] >> 8),
             "  reg sp $sp",
             "  reg pc %d" % S["BattleRound"],
             "}",
             "after time 12 {",
             '  puts $::fh "dexmin [debug read memory %d]"' % S["DexMin"],
             '  set a ""',
             "  for {set i 0} {$i < %d} {incr i} { append a \"[debug read memory [expr %d + $i]] \" }"
             % (PARTY_N, S["ActHero"]),
             '  puts $::fh "acts $a"',
             '  puts $::fh "actmon [debug read memory %d]"' % S["ActMon"],
             '  puts $::fh "seq $::seq"',
             "  close $::fh ; exit",
             "}"]
        open(os.path.join(outdir, name + ".tcl"), "w",
             encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote %d tcl scripts" % len(CASES))


def check(outdir):
    S = syms()
    bad = 0
    for name, (dexes, kind, nmon) in CASES.items():
        mondex = mon_dex(S, kind)
        want_min, want_acts, want_amon, want_seq = model(dexes, mondex, nmon)
        txt = {}
        for line in open(os.path.join(outdir, name + ".txt")).read().split("\n"):
            if line.strip():
                k, _, v = line.partition(" ")
                txt[k] = v.strip()
        got = (int(txt["dexmin"]), [int(v) for v in txt["acts"].split()],
               int(txt["actmon"]), txt["seq"].split())
        want = (want_min, want_acts, want_amon, want_seq)
        if got == want:
            print("%-8s 몬민첩 %2d  최저 %2d  행동수 %s 몬%d  순서 %d 개  OK"
                  % (name, mondex, want_min, want_acts, want_amon, len(want_seq)))
            continue
        bad += 1
        print("%-8s MISMATCH (몬스터 종류 %d, 민첩 %d)" % (name, kind, mondex))
        for lab, g, wv in zip(("최저민첩", "행동수", "몬행동수", "순서"), got, want):
            mark = "OK" if g == wv else "다름"
            print("   %-8s %s  롬 %s" % (lab, mark, g))
            if g != wv:
                print("   %-8s     모델 %s" % ("", wv))
    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    mode, outdir = sys.argv[1], sys.argv[2]
    sys.exit(write_tcl(outdir) if mode == "tcl" else check(outdir))
