"""던전 한 프레임이 창을 **빠짐없이** 덮는가.

일인칭 화면은 프레임마다 창 전체를 새로 그려야 한다. 한 픽셀이라도 안 그리면
그 자리에 앞 프레임 조각이 남는다. 실제로 정면 벽 한가운데에 천장 무늬 한 조각이
남은 화면이 나왔다.

오라클은 간단하다. **창을 표식 하나로 가득 채우고 다시 그린 뒤, 표식이 그대로
남은 픽셀을 센다.** 남으면 그 자리를 아무도 안 그린 것이다. 그림이 어떻게
생겼는지 알 필요가 없어 SCREEN 8 에서도 쓸 수 있다.

표식을 두 번(0xAA, 0x55) 쓴다. 한 번만 쓰면 그 색으로 **정말** 그린 픽셀을
안 그린 것으로 잘못 보게 된다. 두 번 다 남은 자리만 진짜다.

정면 벽은 1 단계가 건너뛰고 2 단계(HMMM)가 붙이므로, 건너뛴 사각형과 붙이는
사각형이 어긋나면 딱 이 검사가 잡는다. 그래서 막힌 거리를 1..MAXD 로 다 돈다.

두 번째 모드(live)는 **진짜로 걸어 다니면서** 같은 것을 본다. 손으로 만든 지도
몇 장으로는 안 나오는 자리가 있을 수 있어서다. 걷다가 이따금 화면을 떠 놓고,
표식으로 덮고 다시 그린 뒤 둘을 견준다. 다르면 그때 화면에 있던 것은 "지금
다시 그리면 나오지 않는 것" - 곧 앞 프레임에서 남은 조각이다.

  uv run python gfx/quest_cover.py tcl   <작업폴더>
  uv run python gfx/quest_cover.py check <작업폴더>
  uv run python gfx/quest_cover.py livetcl   <작업폴더>
  uv run python gfx/quest_cover.py livecheck <작업폴더>
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SYM = os.path.join(HERE, "..", "build", "quest3.sym")

MAP_W = 16
VIEW_X, VIEW_Y, VIEW_W, VIEW_H = 16, 8, 96, 96
MARKS = (0xAA, 0x55)

# (이름, 앞으로 뚫는 칸 수, 옆에 낸 구멍)
#
# **뚫는 칸 수 + 1 이 blockDepth 다** - 뚫은 다음 칸이 벽이라서다. 그래서 0 부터
# 뚫어야 blockDepth 1 (바로 앞이 벽) 을 본다. 검사가 자기가 무엇을 봤는지
# 적으므로(막힘 열), 어긋나면 표에서 바로 보인다.
#
# blockDepth 5 는 MAXD(4) 를 넘어 "끝까지 안 막힘" 이고, 그때는 DrawFront 가
# 아무것도 안 붙이므로 1 단계 혼자 창을 다 덮어야 한다.
# 옆 구멍은 옆면 처리(VIS_*)를 함께 태우려고 넣는다.
CASES = [("d1", 0, []),
         ("d2", 1, [(1, 1)]),
         ("d3", 2, [(-1, 2)]),
         ("d4", 3, [(1, 1), (-1, 3)]),
         ("open", 5, [(1, 2), (-1, 2)])]

START = (7, 12)                 # 북쪽을 보고 선다. 앞으로 y 가 줄어든다.


def syms():
    out = {}
    for line in io.open(SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            out[name] = int(val.strip(), 16)
    return out


def make_map(depth, side):
    """전부 벽으로 채우고 앞으로 depth 칸만 뚫는다."""
    wall = [[1] * MAP_W for _ in range(MAP_W)]
    x0, y0 = START
    wall[y0][x0] = 0
    for k in range(1, depth + 1):
        if 0 <= y0 - k < MAP_W:
            wall[y0 - k][x0] = 0
    for dx, k in side:                      # 옆으로 낸 구멍
        y = y0 - k
        if 0 <= y < MAP_W and 0 <= x0 + dx < MAP_W:
            wall[y][x0 + dx] = 0
    return wall


def fill(mark):
    """창 96 줄을 표식으로 덮는다. 한 줄이 96 바이트다."""
    return ["debug write_block VRAM %d [binary format c* [lrepeat %d %d]]"
            % ((VIEW_Y + r) * 256 + VIEW_X, VIEW_W, mark)
            for r in range(VIEW_H)]


def dumpview(path):
    return ['set f [open "%s" wb]' % path,
            "fconfigure $f -translation binary",
            "puts -nonewline $f [debug read_block VRAM %d %d]"
            % (VIEW_Y * 256, VIEW_H * 256),
            "close $f"]


def write_tcl(outdir):
    S = syms()
    out = outdir.replace(chr(92), "/")
    for name, depth, side in CASES:
        wall = make_map(depth, side)
        w = ["debug write memory %d %d" % (S["MapDataRam"] + y * MAP_W + x, wall[y][x])
             for y in range(MAP_W) for x in range(MAP_W)]
        w += ["debug write memory %d %d" % (S["posX"], START[0]),
              "debug write memory %d %d" % (S["posY"], START[1]),
              "debug write memory %d 0" % S["facing"],
              "debug write memory %d 0" % S["BattleOn"],
              "debug write memory %d 0" % S["MapOn"]]
        L = ["# %s - generated by gfx/quest_cover.py" % name,
             # 걷지는 않지만 굴림이 끼면 화면이 달라진다. 아예 막는다.
             "debug set_bp %d 1 {" % S["RollEncounter"],
             "  set sp [reg sp]",
             "  set lo [debug read memory $sp]",
             "  set hi [debug read memory [expr $sp + 1]]",
             "  reg sp [expr $sp + 2]",
             "  reg pc [expr $lo + $hi * 256]",
             "}",
             "after time 6 { %s ; debug write memory %d 1 }" % (" ; ".join(w), S["needDraw"])]
        t = 7.5
        for i, mark in enumerate(MARKS):
            L += ["after time %.2f { %s ; debug write memory %d 1 }"
                  % (t, " ; ".join(fill(mark)), S["needDraw"]),
                  "after time %.2f { %s }"
                  % (t + 1.0, " ; ".join(dumpview("%s/%s_%d.bin" % (out, name, i))))]
            t += 2.0
        L += ['after time %.2f { set g [open "%s/%s.txt" w] ; '
              'puts $g "depth [debug read memory %d]" ; close $g ; exit }'
              % (t, out, name, S["blockDepth"])]
        io.open(os.path.join(outdir, name + ".tcl"), "w",
                encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote %d tcl scripts" % len(CASES))


def view(path):
    b = io.open(path, "rb").read()
    return [b[r * 256 + VIEW_X:r * 256 + VIEW_X + VIEW_W] for r in range(VIEW_H)]


def check(outdir):
    bad = 0
    for name, depth, _side in CASES:
        txt = dict(l.split(None, 1) for l in
                   io.open(os.path.join(outdir, name + ".txt")).read().split("\n") if l.strip())
        vs = [view(os.path.join(outdir, "%s_%d.bin" % (name, i))) for i in range(len(MARKS))]
        left = [(x, y) for y in range(VIEW_H) for x in range(VIEW_W)
                if all(vs[i][y][x] == MARKS[i] for i in range(len(MARKS)))]
        ok = not left
        print("%-5s 막힘 %s   안 그린 픽셀 %d  %s"
              % (name, txt["depth"], len(left), "OK" if ok else "FAIL"))
        if not ok:
            bad += 1
            xs = [p[0] for p in left]
            ys = [p[1] for p in left]
            print("       창 안 좌표 x %d..%d, y %d..%d (화면으로는 x %d.., y %d..)"
                  % (min(xs), max(xs), min(ys), max(ys),
                     min(xs) + VIEW_X, min(ys) + VIEW_Y))
    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1




# --------------------------------------------------------------------------
# 진짜로 걸어 다니면서 보기
# --------------------------------------------------------------------------
#
# 걸음마다 지도가 바뀌므로 손으로 만든 통로에서는 안 나오는 자리가 있다. 여기서는
# 게임이 만든 진짜 지도를 그대로 쓰고, 키를 눌러 돌아다니다가 이따금 멈춰서
#
#   A = 지금 화면
#   B = 표식으로 덮고 다시 그린 화면
#
# 둘을 견준다. 다르면 A 에 있던 것은 다시 그려서는 나오지 않는 것이다.
#
# 전투는 막는다. 명령 메뉴가 뜨면 메인 루프가 멈춰 있어 needDraw 가 안 먹고,
# 그러면 B 가 표식 그대로라 애먼 실패가 난다. 전투 중 화면은 quest_row 가 본다.
WALK = "FFRFFLFFFRFBFLFFRFF"      # F 앞 B 뒤 L 좌 R 우
LIVE_EVERY = 3                    # 몇 걸음마다 견주는가

WALK_KEY = {"F": "0x20", "B": "0x40", "L": "0x10", "R": "0x80"}


def live_tcl(outdir):
    S = syms()
    out = outdir.replace(chr(92), "/")
    L = ["# live - generated by gfx/quest_cover.py",
         "debug set_bp %d 1 {" % S["RollEncounter"],
         "  set sp [reg sp]",
         "  set lo [debug read memory $sp]",
         "  set hi [debug read memory [expr $sp + 1]]",
         "  reg sp [expr $sp + 2]",
         "  reg pc [expr $lo + $hi * 256]",
         "}",
         'set ::fh [open "%s/live.txt" w]' % out]
    t = 6.5
    n = 0
    for i, c in enumerate(WALK):
        L += ["after time %.2f { keymatrixdown 8 %s }" % (t, WALK_KEY[c]),
              "after time %.2f { keymatrixup   8 %s }" % (t + 0.15, WALK_KEY[c])]
        t += 0.45
        if (i + 1) % LIVE_EVERY == 0:
            L += ["after time %.2f { %s ; puts $::fh \"at %d %s\" }"
                  % (t + 0.3, " ; ".join(dumpview("%s/live%02d_a.bin" % (out, n))),
                     n, c),
                  "after time %.2f { %s ; debug write memory %d 1 }"
                  % (t + 0.5, " ; ".join(fill(MARKS[0])), S["needDraw"]),
                  "after time %.2f { %s }"
                  % (t + 1.3, " ; ".join(dumpview("%s/live%02d_b.bin" % (out, n))))]
            t += 1.8
            n += 1
    L += ["after time %.2f { close $::fh ; exit }" % (t + 0.5)]
    io.open(os.path.join(outdir, "live.tcl"), "w",
            encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote live.tcl (%d 걸음, %d 번 견줌)" % (len(WALK), n))
    return n


def live_check(outdir):
    n = 0
    bad = 0
    while os.path.exists(os.path.join(outdir, "live%02d_a.bin" % n)):
        a = view(os.path.join(outdir, "live%02d_a.bin" % n))
        b = view(os.path.join(outdir, "live%02d_b.bin" % n))
        left = [(x, y) for y in range(VIEW_H) for x in range(VIEW_W)
                if b[y][x] == MARKS[0]]
        diff = [(x, y) for y in range(VIEW_H) for x in range(VIEW_W)
                if a[y][x] != b[y][x]]
        if left:
            print("live%02d 안 그린 픽셀 %d 개  FAIL" % (n, len(left)))
            bad += 1
        elif diff:
            xs = [p[0] for p in diff]
            ys = [p[1] for p in diff]
            print("live%02d 남은 조각 %d 개  x %d..%d, y %d..%d "
                  "(화면 x %d..%d, y %d..%d)  FAIL"
                  % (n, len(diff), min(xs), max(xs), min(ys), max(ys),
                     min(xs) + VIEW_X, max(xs) + VIEW_X,
                     min(ys) + VIEW_Y, max(ys) + VIEW_Y))
            bad += 1
        else:
            print("live%02d 같음  OK" % n)
        n += 1
    if n == 0:
        print("결과가 없습니다")
        return 1
    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    if sys.argv[1] == "tcl":
        write_tcl(sys.argv[2])
    elif sys.argv[1] == "livetcl":
        live_tcl(sys.argv[2])
    elif sys.argv[1] == "livecheck":
        sys.exit(live_check(sys.argv[2]))
    else:
        sys.exit(check(sys.argv[2]))
