"""SCREEN 8 (GRAPHIC 7) 로 옮길 만한지 재 본다. src/questprobe.asm 참고.

종이에서 안 나오는 것은 **대역폭 하나뿐**이라, 그것만 잰다.

  pal   src/questprobepal.asm 을 만든다 (팔레트 -> GRB332)
  tcl   openMSX 스크립트를 만든다
  check 나온 결과를 읽어 표로 낸다

재는 것 세 가지.

1. 간격 - outi 뒤 nop 을 여섯 가지로 두고 96x96 을 그린 시간을 잰다.
   시간은 롬 안에서 재지 않는다. BlitStart / BlitEnd 브레이크포인트에서
   machine_info time 을 빼면 정확하다.
2. 무결성 - 간격이 모자라면 VDP 가 쓰기를 **조용히 흘린다.** 화면을 찍어서는
   모르므로 VRAM 을 되읽어 0..95 그라데이션과 한 바이트씩 맞춰 본다.
   미리 온 화면을 0xFF 로 지워 두었으므로 흘린 자리는 0xFF 로 남는다.
3. 명령 엔진 좌표 - 양피지 창이 전부 HMMV/HMMM 이라, GRAPHIC 7 에서도 x 가
   픽셀 단위이고 CLR 한 바이트가 픽셀 하나인지 확인해야 한다.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SYM = os.path.join(HERE, "..", "build", "questprobe.sym")

sys.path.insert(0, HERE)
import quest_pal                                        # noqa: E402

# src/questprobe.asm 과 같아야 한다
VIEW_W, VIEW_H, BAND_H, NVAR = 96, 96, 28, 7
POISON = 0xFF
PROBE_X, PROBE_Y, PROBE_W, PROBE_H, PROBE_DY = 136, 8, 16, 8, 24
PROBE_COL = 0x1C
VRAM_STRIDE = 256                                       # GRAPHIC 7 은 한 줄 256 바이트
DUMP_ROWS = 212

# 변형별 한 바이트에 드는 T-state (src/questprobe.asm 의 Var0..Var6).
# MSX 의 M1 대기까지 넣은 값이다 - 명령어를 읽을 때마다 1 T 씩 더 든다.
VAR_T = [29.0, 34.0, 44.0, 59.0, 79.0, 109.0, 18 + 11 / 8.0]
VAR_NAME = ["outi+jp", "outi+nop+jp", "outi+3nop", "outi+6nop",
            "outi+10nop", "outi+16nop", "outi x8 (대조군)"]
CONTROL = 6                     # 확실히 너무 빠른 것. 이건 **깨져야** 한다.
Z80_HZ = 3579545.0


def to332(c):
    """RGB333 -> GRB332 한 바이트. R 과 G 는 3 비트 그대로, B 만 4 단계로 준다.

    파랑은 3 비트(8 단계)에서 2 비트(4 단계)로 줄어든다. b>>1 이 아니라 눈금
    자체를 다시 재야 한다 - 4 단계의 눈금은 0, 7/3, 14/3, 7 이다.
    """
    r, g, b = c
    return (g << 5) | (r << 2) | int(round(b * 3.0 / 7.0))


def write_pal(_outdir):
    """src/questprobepal.asm - 팔레트 정본에서 뽑는다. 손으로 옮겨 적지 않는다."""
    L = ["; gfx/questprobe.py 가 gfx/quest_pal.py 에서 만든다. 직접 고치지 말 것.",
         ";",
         "; SCREEN 8 에는 팔레트가 없다. 색이 GRB332 로 못박혀 있어서 R 과 G 는",
         "; 3 비트가 그대로 가고 B 만 3 비트에서 2 비트로 준다.",
         "Pal332:"]
    for i, c in enumerate(quest_pal.PAL333):
        L.append("    db 0x%02X                     ; %2d  RGB333 %d,%d,%d"
                 % (to332(c), i, c[0], c[1], c[2]))
    path = os.path.join(HERE, "..", "src", "questprobepal.asm")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote src/questprobepal.asm")
    return 0


def syms():
    out = {}
    for line in open(SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            out[name] = int(val.strip(), 16)
    return out


def write_tcl(outdir):
    S = syms()
    out = outdir.replace("\\", "/")
    L = ["# generated by gfx/questprobe.py",
         'set ::fh [open "%s/probe.txt" w]' % out,
         "set ::t0 0",
         "set ::c0 0",
         "set ::tf 0",
         # openMSX 21 은 too_fast_vram_access 를 real 로 흉내낸다. 픽셀이
         # 깨졌는지만 보지 말고, VDP 가 "너무 빠르다"고 알려 주는 것도 센다.
         # 인자를 받게 해 둔다. openMSX 가 인자를 붙여 부르면 인자 없는 proc 은
         # 조용히 오류가 나고, 그러면 "경고 0 번" 이 콜백이 안 불린 탓인지
         # 정말 안 걸린 탓인지 알 수가 없다.
         "proc tfva {args} { incr ::tf }",
         "set ::VDP.too_fast_vram_access_callback tfva",
         # 카나리아 - 확실히 너무 빠른 쓰기(3.35 us)가 정말 걸리는지 본다.
         "debug set_bp %d 1 { set ::tf 0 }" % S["CanaryStart"],
         "debug set_bp %d 1 {" % S["CanaryEnd"],
         '  puts $::fh "canary $::tf"',
         '  puts $::fh "cbset [set ::VDP.too_fast_vram_access_callback]"',
         "  flush $::fh",
         "}",
         # 같은 간격의 **읽기**. 여기서도 안 걸리면 이 고장 자체를 안 보는 것이다.
         "debug set_bp %d 1 { set ::tf 0 }" % S["CanaryRStart"],
         "debug set_bp %d 1 { puts $::fh \"canaryr $::tf\" ; flush $::fh }"
         % S["CanaryREnd"],
         # 명령 엔진이 도는 중에 같은 간격으로 쓰기.
         "debug set_bp %d 1 { set ::tf 0 }" % S["CanaryCStart"],
         "debug set_bp %d 1 { puts $::fh \"canaryc $::tf\" ; flush $::fh }"
         % S["CanaryCEnd"],
         # 같은 쓰기 카나리아를 GRAPHIC 4 에서도.
         "debug set_bp %d 1 { set ::tf 0 }" % S["Canary4Start"],
         "debug set_bp %d 1 {" % S["Canary4End"],
         '  puts $::fh "canary4 $::tf"',
         "  flush $::fh",
         "}",
         # VDP 명령 엔진으로 같은 넓이를 다루면 얼마나 걸리나.
         "debug set_bp %d 1 { set ::c0 [machine_info time] }" % S["HmmmStart"],
         "debug set_bp %d 1 {" % S["HmmmEnd"],
         '  puts $::fh "hmmm [expr [machine_info time] - $::c0]"',
         "  set ::c0 [machine_info time]",
         "  flush $::fh",
         "}",
         "debug set_bp %d 1 { puts $::fh \"hmmv [expr [machine_info time]"
         " - $::c0]\" ; flush $::fh }" % S["HmmvEnd"],
         # BlitStart 에서 시각을 잡고 BlitEnd 에서 뺀다. 롬 안에 시계를 넣는
         # 것보다 정확하고, 재는 코드가 재는 대상을 늦추지도 않는다.
         "debug set_bp %d 1 { set ::t0 [machine_info time] ; set ::tf 0 }"
         % S["BlitStart"],
         "debug set_bp %d 1 {" % S["BlitEnd"],
         "  set v [debug read memory %d]" % S["Variant"],
         "  puts $::fh \"time $v [expr [machine_info time] - $::t0] $::tf\"",
         "  flush $::fh",
         "}",
         "debug set_bp %d 1 {" % S["ProbeDone"],
         # 이 openMSX 에는 debug save_to_file 이 없다. read_block 은 바이트열을
         # 통째로 돌려주므로 파일로 직접 쓴다 - 5 만 번 debug read 를 도는 것보다
         # 비교가 안 되게 빠르다.
         '  set vf [open "%s/vram.bin" w]' % out,
         "  fconfigure $vf -translation binary",
         "  puts -nonewline $vf [debug read_block VRAM 0 %d]"
         % (VRAM_STRIDE * DUMP_ROWS),
         "  close $vf",
         "}",
         # 카나리아 셋은 덤프 뒤에 돈다(모드를 바꾸면 VRAM 배치가 어긋난다).
         "debug set_bp %d 1 { close $::fh ; exit }" % S["AllDone"],
         "after time 20 { close $::fh ; exit }"]      # 안전장치
    open(os.path.join(outdir, "probe.tcl"), "w",
         encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote probe.tcl")
    return 0


# --------------------------------------------------------------------------
# 견줄 값 - 지금 SCREEN 5 의 던전 한 장은 몇 ms 인가
# --------------------------------------------------------------------------
# "SCREEN 8 이면 84 ms" 만으로는 결정을 못 한다. 지금이 얼마인지 옆에 있어야
# 두 배인지 다섯 배인지가 보인다. quest.rom 을 그대로 띄워 RenderDungeon 을
# 같은 방법(machine_info time)으로 잰다. 끝나는 자리는 스택의 복귀 주소로 찾는다.
#
# **지도를 못박아 둔다.** 처음에는 부팅한 그대로 세 장을 재서 가장 짧은 것을
# 썼는데, 그건 층이 부팅마다 달라지는 값의 최솟값일 뿐이다. RenderDungeon 은
# 앞이 가까이 막히면 가운데를 통째로 건너뛰므로(VIS_SKIP), 재는 자리에 따라
# 옮기는 바이트가 크게 다르다. 가장 짧은 것을 고르면 **가장 싼 화면**을 기준으로
# 삼는 셈이라 어림이 낙관적으로 기운다. verify_quest_sides.ps1 이 쓰는 지도를
# 그대로 가져다 넓은 방과 좁은 통로를 둘 다 잰다.
QUEST_SYM = os.path.join(HERE, "..", "build", "quest.sym")
# SCREEN 8 판을 재려면 여기를 quest3.sym 으로 바꾼다(같은 심볼 이름을 쓴다).
if os.environ.get("QUEST_ROM") == "quest3":
    QUEST_SYM = os.path.join(HERE, "..", "build", "quest3.sym")
REF_CASES = ["plaza", "far2", "branch", "near"]
# plaza 넓은 방 / far2 멀리 벽 / branch 좁은 통로 / near 코앞이 벽.
# near 를 꼭 넣어야 한다 - 정면 벽이 제일 큰(73x73) 화면이 이것뿐이라, 정면
# 벽을 VDP 에 넘긴 효과가 나머지 셋에서는 거의 안 보인다.


def ref_tcl(outdir):
    import quest_sides
    q = {}
    for line in open(QUEST_SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            q[name] = int(val.strip(), 16)
    out = outdir.replace("\\", "/")
    L = ["# generated by gfx/questprobe.py",
         'set ::fh [open "%s/ref.txt" w]' % out,
         "set ::t0 0",
         "set ::case none",
         "set ::armed 0",
         # 런이 한 장에 몇 개인가. VDP 명령으로 그리려면 런마다 명령 하나가
         # 필요하고, 명령 하나에 드는 준비 시간(약 520 T = 0.15 ms)이 그 수만큼
         # 곱해진다. 이 수를 모르면 "VDP 에 시키면 빠르다"는 말을 할 수 없다.
         "set ::runs 0",
         "debug set_bp %d 1 { incr ::runs }" % q["RenderDungeon.run"],
         "debug set_bp %d 1 {" % q["RenderDungeon"],
         "  set ::t0 [machine_info time]",
         "  set ::runs 0",
         "  if {$::armed} { return }",
         "  set ::armed 1",
         "  set sp [reg sp]",
         "  set r [expr [debug read memory $sp] + 256 * [debug read memory"
         " [expr $sp + 1]]]",
         '  debug set_bp $r 1 { puts $::fh "ref $::case [expr'
         ' [machine_info time] - $::t0] $::runs" ; flush $::fh }',
         "}"]
    t = 7.0
    for name in REF_CASES:
        grid, px, py, f = quest_sides.CASES[name]
        w = ["debug write memory %d %d" % (q["MapDataRam"] + y * 16 + x,
                                           1 if grid[y][x] == "#" else 0)
             for y in range(16) for x in range(16)]
        w += ["debug write memory %d %d" % (q["posX"], px),
              "debug write memory %d %d" % (q["posY"], py),
              "debug write memory %d %d" % (q["facing"], f),
              "debug write memory %d 0" % q["BattleOn"],
              "debug write memory %d 1" % q["needDraw"]]
        L.append("after time %.2f { set ::case %s ; %s }"
                 % (t, name, " ; ".join(w)))
        t += 1.0
    L.append("after time %.2f { close $::fh ; exit }" % t)
    open(os.path.join(outdir, "ref.tcl"), "w",
         encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote ref.tcl (%s)" % ", ".join(REF_CASES))
    return 0


def ref_ms(outdir):
    """지도를 못박고 잰 SCREEN 5 기준값. {이름: ms}. 한 지도를 여러 번 재면
    같은 값이 나오므로 마지막 것을 쓴다."""
    path = os.path.join(outdir, "ref.txt")
    if not os.path.exists(path):
        return {}
    out = {}
    for line in open(path).read().split("\n"):
        if line.startswith("ref "):
            _, name, t, runs = line.split()
            if name != "none":
                out[name] = (float(t) * 1000.0, int(runs))
    return out


def check(outdir):
    times, canary, canary4, canaryr, canaryc, cbset = {}, -1, -1, -1, -1, ""
    cmd = {}
    for line in open(os.path.join(outdir, "probe.txt")).read().split("\n"):
        if line.startswith("time "):
            _, v, t, tf = line.split()
            times[int(v)] = (float(t), int(tf))
        elif line.startswith("canary "):
            canary = int(line.split()[1])
        elif line.startswith("canary4 "):
            canary4 = int(line.split()[1])
        elif line.startswith("canaryr "):
            canaryr = int(line.split()[1])
        elif line.startswith("canaryc "):
            canaryc = int(line.split()[1])
        elif line.startswith("cbset "):
            cbset = line.split(None, 1)[1].strip()
        elif line.startswith("hmmm ") or line.startswith("hmmv "):
            k, t = line.split()
            cmd[k] = float(t) * 1000.0
    vram = open(os.path.join(outdir, "vram.bin"), "rb").read()
    if len(vram) < VRAM_STRIDE * DUMP_ROWS:
        print("VRAM 덤프가 %d 바이트뿐이다" % len(vram))
        return 1

    def px(x, y):
        return vram[y * VRAM_STRIDE + x]

    bad = 0

    # ---- 1+2. 간격마다 걸린 시간과 흘린 바이트 -------------------------------
    print("변형  안쪽 고리          T/바이트    us     96x96     프레임  흘림  VDP경고")
    ok_var, lost_of = None, {}
    for v in range(NVAR):
        lost = first = 0
        for row in range(BAND_H):
            y = v * BAND_H + row
            for x in range(VIEW_W):
                if px(x, y) != x:
                    lost += 1
                    if lost == 1:
                        first = (x, y)
        lost_of[v] = lost
        t, tf = times.get(v, (float("nan"), -1))
        ms = t * 1000.0
        print("  %d   %-18s %5.1f T  %5.1f  %7.1f ms  %5.1f  %5d  %7d"
              % (v, VAR_NAME[v], VAR_T[v], VAR_T[v] / Z80_HZ * 1e6,
                 ms, ms / 16.67, lost, tf))
        if lost == 0 and tf == 0 and ok_var is None and v != CONTROL:
            ok_var = v

    # ---- 견줄 값과 어림 -----------------------------------------------------
    # 위 표의 84 ms 를 지금 것과 곧장 견주면 안 된다. 저것은 96x96 을 그냥 밀어
    # 넣은 값이고, 지금 RenderDungeon 은 가시성 계산과 런 해독까지 다 한다.
    # 옳게 견주는 방법: SCREEN 8 은 픽셀 수만 두 배(4,608 -> 9,216 바이트)이고
    # 나머지 일은 그대로다. 그러니 **늘어나는 것은 4,608 바이트 값어치뿐**이다.
    # ---- VDP 명령 엔진 -----------------------------------------------------
    # Z80 이 바이트를 미는 대신 VDP 에게 시키면, 벽면 자료를 롬이 아니라 VRAM 에
    # 둘 수 있다. SCREEN 8 페이지 0 이 64KB 라 128KB 중 64KB 가 남는다.
    if cmd:
        print("\n같은 넓이(96x96 = 9,216 픽셀)를 VDP 명령 엔진에 시키면")
        best = min(times[v][0] for v in range(NVAR)) * 1000.0
        for k, label in (("hmmm", "HMMM (VRAM 안에서 복사)"),
                         ("hmmv", "HMMV (단색 채우기)")):
            if k in cmd:
                print("   %-22s %6.1f ms   Z80 이 미는 것보다 %.1f 배 %s"
                      % (label, cmd[k], max(cmd[k], best) / min(cmd[k], best),
                         "빠르다" if cmd[k] < best else "느리다"))
        print("   (Z80 이 제일 빠른 간격으로 밀었을 때가 %.1f ms)" % best)

    ref = ref_ms(outdir)
    if ref:
        print("\n견줄 값: 지금 SCREEN 5 의 RenderDungeon (지도를 못박고 잰 값)")
        for name in REF_CASES:
            if name in ref:
                ms, runs = ref[name]
                print("   %-8s %6.1f ms (%.1f 프레임)   런 %d 개"
                      % (name, ms, ms / 16.67, runs))
        worst = max(v[0] for v in ref.values())
        wruns = max(v[1] for v in ref.values())
        if cmd.get("hmmm"):
            # 런마다 명령을 하나 보내야 한다. 준비 시간은 SendCmd 한 번 값 -
            # WaitVdpCmd + R#17 쓰기 + otir 15 바이트 = 대략 520 T.
            setup = wruns * 520 / Z80_HZ * 1000.0
            print("   VDP 명령으로 그리면: 픽셀 %.1f ms + 명령 준비 %d x 0.15 ="
                  " %.1f ms -> 약 %.1f ms"
                  % (cmd["hmmm"], wruns, setup, cmd["hmmm"] + setup))
        print("   SCREEN 8 은 픽셀만 두 배다(4608 -> 9216 바이트). 나머지 일은 같다.")
        print("   아래는 그중 가장 무거운 화면(%.1f ms)에 얹은 값이다." % worst)
        for v in (1, 3, 4):
            add = 4608 * VAR_T[v] / Z80_HZ * 1000.0
            print("   간격 %5.1f us 면  +%5.1f ms  ->  %6.1f ms (%.1f 프레임)%s"
                  % (VAR_T[v] / Z80_HZ * 1e6, add, worst + add,
                     (worst + add) / 16.67,
                     "   <- 지금 쓰는 간격" if v == 1 else ""))

    print("\n카나리아 (out (n),a = 12 T = 3.35 us. 어떤 모드에서도 너무 빠르다)")
    print("   쓰기 G7 %d, 쓰기 G4 %d, 읽기 G7 %d, 명령중 쓰기 %d  (콜백 = %s)"
          % (canary, canary4, canaryr, canaryc, cbset or "(빈 값)"))
    if canary == 0 and canary4 == 0 and canaryr == 0 and canaryc == 0:
        # 확실히 너무 빠른 접근조차 안 걸린다. 이것은 이 코드의 잘못이 아니라
        # **이 측정으로 답할 수 없는 항목**이다. 그래서 FAIL 로 세지 않고
        # 주의로 남긴다 - 대신 위 '흘림' 칸을 근거로 삼아서는 안 된다.
        print("   주의: 확실히 너무 빠른 접근조차 한 번도 안 걸렸다. 이 openMSX 는")
        print("   화면 표시와의 VRAM 다툼을 흉내내지 않는다. 따라서 위 '흘림' 과")
        print("   'VDP경고' 칸은 **최소 간격의 근거가 못 된다** - 그것만은 실기에서")
        print("   확인해야 한다. 걸린 시간 칸은 T-state 계산과 0.4% 안에서 맞으므로")
        print("   그대로 믿을 수 있다.")
    elif ok_var is None:
        bad += 1
        print("   어떤 간격으로도 온전히 안 들어갔다 - 변형을 더 늘려야 한다")
    else:
        print("   온전히 들어가는 가장 짧은 간격: 변형 %d (%.0f T = %.1f us)"
              % (ok_var, VAR_T[ok_var], VAR_T[ok_var] / Z80_HZ * 1e6))
        print("   그때 96x96 한 장 = %.1f ms (%.1f 프레임). "
              "대조군은 %d 바이트 흘리고 경고 %d 번."
              % (times[ok_var][0] * 1000, times[ok_var][0] * 1000 / 16.67,
                 lost_of[CONTROL], times[CONTROL][1]))

    # ---- 3. 명령 엔진 좌표 --------------------------------------------------
    print()
    for label, y0 in (("HMMV", PROBE_Y), ("HMMM", PROBE_DY)):
        inside = all(px(x, y) == PROBE_COL
                     for y in range(y0, y0 + PROBE_H)
                     for x in range(PROBE_X, PROBE_X + PROBE_W))
        edges = (px(PROBE_X - 1, y0) == POISON and
                 px(PROBE_X + PROBE_W, y0) == POISON)
        if inside and edges:
            print("%s  x=%d..%d 딱 그만큼 칠해졌다 - 좌표는 픽셀 단위, "
                  "CLR 한 바이트 = 한 픽셀  OK"
                  % (label, PROBE_X, PROBE_X + PROBE_W - 1))
        else:
            bad += 1
            got = [px(x, y0) for x in range(PROBE_X - 2, PROBE_X + PROBE_W + 2)]
            print("%s  MISMATCH - y=%d 의 x=%d.. 바이트: %s"
                  % (label, y0, PROBE_X - 2, " ".join("%02X" % b for b in got)))

    # ---- 4. 색 - 16 색이 GRB332 에서 몇 가지로 남는가 -----------------------
    # SCREEN 8 에는 팔레트가 없다. R 과 G 는 3 비트가 그대로 가지만 파랑은
    # 4 단계뿐이라, 파랑만 다른 두 색은 **같은 색이 된다.** 화면 아래 견본에서
    # 눈으로도 보이지만 숫자로도 남겨 둔다.
    print()
    seen = {}
    for i, c in enumerate(quest_pal.PAL333):
        seen.setdefault(to332(c), []).append(i)
    dup = {k: v for k, v in seen.items() if len(v) > 1}
    print("팔레트 16색 -> GRB332 에서 %d 가지로 남는다" % len(seen))
    for byte, idx in sorted(dup.items()):
        print("   0x%02X 에서 겹침: %s"
              % (byte, ", ".join("%d(%d,%d,%d)" % ((i,) + quest_pal.PAL333[i])
                                 for i in idx)))
    if not dup:
        print("   겹치는 색 없음")

    print("\nPASS" if bad == 0 else "\nFAIL")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    mode, outdir = sys.argv[1], sys.argv[2]
    sys.exit({"pal": write_pal, "tcl": write_tcl, "check": check,
              "reftcl": ref_tcl}[mode](outdir))
