"""생성된 던전이 언제나 하나로 이어져 있는지 확인한다.

questlevel.asm 은 "새 방을 직전 방과 항상 연결"하므로 결과가 늘 하나의 연결
성분이어야 한다 - 그렇지 않으면 못 가는 방이 생긴다. 예전에는 부팅 몇 번 해 보고
손으로 BFS 를 돌려 확인했는데, 그 확인을 통과한 채로 연결이 끊기는 버그가 살아
있었다(LinkRooms 의 가로-먼저 갈래가 CarveV 에 인자를 뒤바꿔 넘겼다).

부팅마다 지도가 하나뿐이면 표본이 너무 적다. 그래서 **한 번 부팅해서 지도를 수십
장 만든다.** MainLoop 에 브레이크포인트를 걸고, 걸릴 때마다 Seed 를 정해 놓은
값으로 바꾼 뒤 되돌아올 주소를 스택에 넣고 PC 를 MakeLevel 로 돌린다. MakeLevel
이 ret 하면 다시 MainLoop 라 브레이크포인트가 또 걸린다.

  uv run --with pillow python gfx/quest_mapcheck.py tcl   <작업폴더>
  uv run --with pillow python gfx/quest_mapcheck.py check <작업폴더>
"""
import os
import sys
from collections import deque

MAP_W = 16
N_MAPS = 48

SYM = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "build", "quest.sym")


def syms():
    out = {}
    for line in open(SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            out[name] = int(val.strip(), 16)
    return out


def seeds():
    """xorshift 는 0 을 못 쓰므로 0 은 피한다. 값 자체는 아무래도 좋다."""
    s, out = 0x1234, []
    for _ in range(N_MAPS):
        s ^= (s << 7) & 0xFFFF
        s ^= s >> 9
        s ^= (s << 8) & 0xFFFF
        out.append(s or 0xACE1)
    return out


def write_tcl(outdir):
    S = syms()
    dump = os.path.join(outdir, "maps.txt").replace("\\", "/")
    lo, hi = S["MainLoop"] & 0xFF, S["MainLoop"] >> 8
    L = [
        "# generated by gfx/quest_mapcheck.py",
        'set ::fh [open "%s" w]' % dump,
        "set ::n 0",
        "set ::seeds { %s }" % " ".join(str(v) for v in seeds()),
        # Tcl 은 한 명령이 줄에서 끝나므로 for 의 본문을 다음 줄로 내리면 안 된다.
        "debug set_bp %d 1 {" % S["MainLoop"],
        "  if {$::n > 0} {",
        "    set s \"\"",
        "    for {set i 0} {$i < %d} {incr i} { append s \"[debug read memory [expr %d + $i]] \" }"
        % (MAP_W * MAP_W, S["MapDataRam"]),
        "    puts $::fh \"map [debug read memory %d] [debug read memory %d] $s\""
        % (S["posX"], S["posY"]),
        "    flush $::fh",
        "  }",
        "  if {$::n == [llength $::seeds]} { close $::fh ; exit }",
        "  set sd [lindex $::seeds $::n]",
        "  debug write memory %d [expr $sd & 255]" % S["Seed"],
        "  debug write memory %d [expr ($sd >> 8) & 255]" % (S["Seed"] + 1),
        "  set sp [expr [reg sp] - 2]",          # 되돌아올 주소를 직접 밀어 넣는다
        "  debug write memory $sp %d" % lo,
        "  debug write memory [expr $sp + 1] %d" % hi,
        "  reg sp $sp",
        "  reg pc %d" % S["MakeLevel"],
        "  incr ::n",
        "}",
        "after time 30 { close $::fh ; exit }",   # 안전장치
    ]
    open(os.path.join(outdir, "mapcheck.tcl"), "w",
         encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote mapcheck.tcl (%d maps)" % N_MAPS)


def components(cells):
    seen, comps = set(), []
    for c in cells:
        if c in seen:
            continue
        q, comp = deque([c]), []
        seen.add(c)
        while q:
            x, y = q.popleft()
            comp.append((x, y))
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                n = (x + dx, y + dy)
                if n in cells and n not in seen:
                    seen.add(n)
                    q.append(n)
        comps.append(comp)
    return sorted(comps, key=len, reverse=True)


def check(outdir):
    bad = 0
    lines = [l for l in open(os.path.join(outdir, "maps.txt")).read().split("\n")
             if l.startswith("map ")]
    if len(lines) != N_MAPS:
        print("지도가 %d 장뿐이다 (%d 장이어야 함)" % (len(lines), N_MAPS))
        return 1
    for k, line in enumerate(lines):
        v = [int(t) for t in line.split()[1:]]
        px, py, cells = v[0], v[1], v[2:]
        floor = {(x, y) for y in range(MAP_W) for x in range(MAP_W)
                 if cells[y * MAP_W + x] == 0}
        comps = components(floor)
        ok = len(comps) == 1 and (px, py) in floor
        if not ok:
            bad += 1
            print("지도 %d: 통로 %d 칸, 연결 성분 %d 개, 시작 (%d,%d)"
                  % (k, len(floor), len(comps), px, py))
            if bad <= 2:
                for y in range(MAP_W):
                    row = ""
                    for x in range(MAP_W):
                        if (x, y) == (px, py):
                            row += "@"
                        elif (x, y) not in floor:
                            row += "#"
                        else:
                            row += "." if (x, y) in comps[0] else "X"
                    print("   " + row)
                print("   (X = 시작 위치에서 갈 수 없는 칸)")
    print("지도 %d 장 중 끊긴 것 %d 장" % (N_MAPS, bad))
    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1


# --------------------------------------------------------------------------
# 안개 걷기 - 걸은 자리 둘레 3x3 만 지도에 남는가
# --------------------------------------------------------------------------
# 곧은 통로 x=7, y=4..9 에 왼쪽 옆길 하나. 북쪽으로 세 걸음 걷는다.
FOG_OPEN = [(7, y) for y in range(4, 10)] + [(6, 6), (5, 6)]
FOG_START = (7, 8)
FOG_STEPS = 3


def fog_tcl(outdir):
    S = syms()
    wall = [[1] * MAP_W for _ in range(MAP_W)]
    for x, y in FOG_OPEN:
        wall[y][x] = 0
    w = ["debug write memory %d %d" % (S["MapDataRam"] + y * MAP_W + x, wall[y][x])
         for y in range(MAP_W) for x in range(MAP_W)]
    w += ["debug write memory %d 0" % (S["SeenRam"] + i) for i in range(MAP_W * MAP_W)]
    w += ["debug write memory %d %d" % (S["posX"], FOG_START[0]),
          "debug write memory %d %d" % (S["posY"], FOG_START[1]),
          "debug write memory %d 0" % S["facing"],
          "debug write memory %d 0" % S["BattleOn"]]

    L = ["# generated by gfx/quest_mapcheck.py",
         # 걷다 보면 여덟 칸에 한 번꼴로 몬스터를 만난다. 전투가 걸리면 그 뒤의
         # 방향키를 이동으로 안 받아서 걸음 수가 모자라고, 예전에는 운이 좋아
         # 통과했을 뿐이다. RollEncounter 를 입구에서 되돌려 아예 막는다.
         "debug set_bp %d 1 {" % S["RollEncounter"],
         "  set sp [reg sp]",
         "  set lo [debug read memory $sp]",
         "  set hi [debug read memory [expr $sp + 1]]",
         "  reg sp [expr $sp + 2]",
         "  reg pc [expr $lo + $hi * 256]",
         "}",
         "after time 7 { %s }" % " ; ".join(w)]
    t = 7.4

    def key(mask, when):
        return ["after time %.2f { keymatrixdown 8 %s }" % (when, mask),
                "after time %.2f { keymatrixup 8 %s }" % (when + 0.15, mask)]

    # 제자리 회전 두 번 - 움직이지 않고 시작 자리를 드러낸다
    L += key("0x10", t); t += 0.6
    L += key("0x80", t); t += 0.6
    for _ in range(FOG_STEPS):
        L += key("0x20", t); t += 0.7                    # 위 = 전진
    L.append("after time %.2f {" % t)
    L.append('  set fh [open "%s/fog.txt" w]' % os.path.join(outdir).replace("\\", "/"))
    L.append('  puts $fh "pos [debug read memory %d] [debug read memory %d]"'
             % (S["posX"], S["posY"]))
    L.append('  set s ""')
    L.append("  for {set i 0} {$i < %d} {incr i} { append s \"[debug read memory [expr %d + $i]] \" }"
             % (MAP_W * MAP_W, S["SeenRam"]))
    L.append('  puts $fh "seen $s"')
    L.append("  close $fh")
    L.append("}")
    L.append("after time %.2f { exit }" % (t + 0.5))
    open(os.path.join(outdir, "fog.tcl"), "w",
         encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote fog.tcl")


def fog_check(outdir):
    txt = open(os.path.join(outdir, "fog.txt")).read().split("\n")
    px, py = (int(v) for v in txt[0].split()[1:])
    seen = [int(v) for v in txt[1].split()[1:]]
    visited = [(FOG_START[0], FOG_START[1] - k) for k in range(FOG_STEPS + 1)]
    want = {(x + dx, y + dy) for x, y in visited
            for dx in (-1, 0, 1) for dy in (-1, 0, 1)
            if 0 <= x + dx < MAP_W and 0 <= y + dy < MAP_W}
    got = {(x, y) for y in range(MAP_W) for x in range(MAP_W) if seen[y * MAP_W + x]}
    end = (FOG_START[0], FOG_START[1] - FOG_STEPS)
    if got == want and (px, py) == end:
        print("안개: 세 걸음 뒤 드러난 칸 %d 개 - 기대와 같음  PASS" % len(got))
        return 0
    print("안개: 끝 위치 (%d,%d), 기대 (%d,%d)" % (px, py, end[0], end[1]))
    print("  더 드러남:", sorted(got - want))
    print("  덜 드러남:", sorted(want - got))
    for y in range(MAP_W):
        print("   " + "".join("O" if (x, y) in got else ("x" if (x, y) in want else ".")
                              for x in range(MAP_W)))
    print("  (O = 드러남, x = 드러나야 하는데 아닌 칸)")
    print("FAIL")
    return 1


if __name__ == "__main__":
    mode, outdir = sys.argv[1], sys.argv[2]
    sys.exit({"tcl": write_tcl, "check": check,
              "fogtcl": fog_tcl, "fogcheck": fog_check}[mode](outdir))
