"""민첩이 정하는 전투 행동 횟수를 확인한다 (quest_sena.md 의 전투방식).

  행동 횟수 = floor(내 민첩 / 이 전장의 최저 민첩)

한 라운드는 여러 바퀴로 돈다. 첫 바퀴에는 모두, 둘째 바퀴에는 두 번 이상 움직일
것만, ... 아무도 못 움직이는 바퀴가 나오면 라운드 끝. 바퀴 안에서는 예전처럼
우리 편 하나 / 상대 하나로 번갈아 간다.

민첩을 정해 놓고 한 라운드를 돌린 뒤, **누가 몇 번째로 쳤는지 순서 전체**를
HeroAttack / MonAttack 브레이크포인트로 받아 적어 파이썬 모델과 대조한다.

두 가지를 알고 맞춰 두었다.

  - 몬스터 민첩은 MonsterTable 에 있고 그건 **롬**이라 debug write 로 못 바꾼다.
    그래서 종류를 골라 쓰고, 그 종류의 민첩은 빌드된 롬에서 직접 읽어 온다.
  - 브레이크포인트는 루틴 **입구**에서 걸리므로 죽은 몬스터의 호출도 잡힌다
    (MonAttack 이 안에서 바로 돌아간다). 모델도 그렇게 센다.

  uv run python gfx/quest_turns.py tcl   <작업폴더>
  uv run python gfx/quest_turns.py check <작업폴더>
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SYM = os.path.join(HERE, "..", "build", "quest.sym")
ROM = os.path.join(HERE, "..", "build", "quest.rom")
PARTY_N, MON_N = 6, 5
MON_TSTRIDE, T_DEX = 21, 6
BIG_HP = 255

# 파티 기록 오프셋 (questrules.asm 과 같아야 한다)
P_DEX, P_HP, P_MAXHP, P_AC, P_ATK, P_DCNT, P_DSIDE, P_DMOD = 15, 21, 22, 23, 24, 25, 26, 27
PARTY_STRIDE, MON_STRIDE = 32, 4

# (사람 여섯의 민첩, 몬스터 종류, 살아 있는 마릿수)
CASES = {
    "even":    ([10, 10, 10, 10, 10, 10], 2, 3),   # 모두 비슷하면 모두 한 번씩
    "split":   ([15, 5, 10, 12, 5, 9], 1, 2),      # 최저 5 - 15 인 사람은 세 번
    "slowmon": ([18, 17, 16, 15, 14, 13], 1, 2),   # 몬스터가 제일 굼뜨다
    "fastmon": ([6, 6, 7, 6, 8, 6], 4, 4),         # 몬스터가 제일 빠르다
    "zero":    ([0, 6, 6, 6, 6, 6], 1, 1),         # 민첩 0 - 0 으로 나누면 안 된다
}


def syms():
    out = {}
    for line in open(SYM, encoding="utf-8"):
        if ": EQU 0x" in line:
            name, val = line.split(": EQU 0x")
            out[name] = int(val.strip(), 16)
    return out


def mon_dex(S, kind):
    """빌드된 롬에서 그 종류의 민첩을 읽는다. 본체는 0x4000 에 놓인다."""
    rom = open(ROM, "rb").read()
    return rom[S["MonsterTable"] - 0x4000 + kind * MON_TSTRIDE + T_DEX]


def model(dexes, mondex, nmon):
    alive = list(dexes) + [mondex] * nmon
    dmin = max(1, min(alive))
    acts = [max(1, d // dmin) for d in dexes]
    amon = max(1, mondex // dmin)
    seq, p = [], 1
    while True:
        acted = False
        for i in range(max(PARTY_N, MON_N)):
            if i < PARTY_N and acts[i] >= p:
                seq.append("H%d" % i)
                acted = True
            if i < MON_N and amon >= p:       # 죽은 몬스터도 호출은 된다
                seq.append("M%d" % i)
                acted = True
        if not acted:
            break
        p += 1
    return dmin, acts, amon, seq


def write_tcl(outdir):
    S = syms()
    for name, (dexes, kind, nmon) in CASES.items():
        w = []
        for i, d in enumerate(dexes):
            b = S["Party"] + i * PARTY_STRIDE
            w += ["debug write memory %d %d" % (b + P_DEX, d),
                  "debug write memory %d %d" % (b + P_HP, BIG_HP),
                  "debug write memory %d %d" % (b + P_MAXHP, BIG_HP),
                  "debug write memory %d 30" % (b + P_AC),      # 거의 안 맞게
                  "debug write memory %d 0" % (b + P_ATK),
                  "debug write memory %d 1" % (b + P_DCNT),     # 피해 1 - 아무도
                  "debug write memory %d 1" % (b + P_DSIDE),    # 안 죽어야 순서만
                  "debug write memory %d 0" % (b + P_DMOD)]     # 남는다
        for i in range(MON_N):
            b = S["Monsters"] + i * MON_STRIDE
            hp = BIG_HP if i < nmon else 0
            w += ["debug write memory %d %d" % (b + 1, hp),
                  "debug write memory %d %d" % (b + 2, hp)]
        w += ["debug write memory %d %d" % (S["MonCount"], nmon),
              "debug write memory %d %d" % (S["MonKind"], kind),
              "debug write memory %d 1" % S["BattleOn"],
              "debug write memory %d 1" % S["RoundNo"]]
        out = os.path.join(outdir, name + ".txt").replace(chr(92), "/")
        L = ["# %s - generated by gfx/quest_turns.py" % name,
             'set ::fh [open "%s" w]' % out,
             "set ::seq {}",
             "set ::go 0",
             "after time 7 { %s ; set ::go 1 }" % " ; ".join(w),
             # AskCommand 는 사람 입력을 기다린다. 순서만 보는 검사라 바로
             # 돌려보내고 A=0(공격)으로 만든다 - 스택의 복귀 주소로 뛴다.
             "debug set_bp %d 1 {" % S["AskCommand"],
             # 입구에서 바로 나가므로 AskCommand 가 하던 일(MenuHero 기록)을
             # 여기서 대신 해 준다. 안 하면 늘 0 번 사람이 치는 것으로 보인다.
             "  debug write memory %d [reg a]" % S["MenuHero"],
             "  set sp [reg sp]",
             "  set lo [debug read memory $sp]",
             "  set hi [debug read memory [expr $sp + 1]]",
             "  reg sp [expr $sp + 2]",
             "  reg pc [expr $lo + $hi * 256]",
             "  reg a %d" % 0,
             "}",
             "debug set_bp %d 1 { if {$::go == 2} { lappend ::seq H[reg a] } }"
             % S["HeroAttack"],
             "debug set_bp %d 1 { if {$::go == 2} { lappend ::seq M[reg a] } }"
             % S["MonAttack"],
             "debug set_bp %d 1 {" % S["MainLoop"],
             "  if {$::go != 1} { return }",
             "  set ::go 2",
             "  set sp [expr [reg sp] - 2]",
             "  debug write memory $sp %d" % (S["MainLoop"] & 0xFF),
             "  debug write memory [expr $sp + 1] %d" % (S["MainLoop"] >> 8),
             "  reg sp $sp",
             "  reg pc %d" % S["BattleRound"],
             "}",
             "after time 12 {",
             '  puts $::fh "dexmin [debug read memory %d]"' % S["DexMin"],
             '  set a ""',
             "  for {set i 0} {$i < %d} {incr i} { append a \"[debug read memory [expr %d + $i]] \" }"
             % (PARTY_N, S["ActHero"]),
             '  puts $::fh "acts $a"',
             '  puts $::fh "actmon [debug read memory %d]"' % S["ActMon"],
             '  puts $::fh "seq $::seq"',
             "  close $::fh ; exit",
             "}"]
        open(os.path.join(outdir, name + ".tcl"), "w",
             encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote %d tcl scripts" % len(CASES))


def check(outdir):
    S = syms()
    bad = 0
    for name, (dexes, kind, nmon) in CASES.items():
        mondex = mon_dex(S, kind)
        want_min, want_acts, want_amon, want_seq = model(dexes, mondex, nmon)
        txt = {}
        for line in open(os.path.join(outdir, name + ".txt")).read().split("\n"):
            if line.strip():
                k, _, v = line.partition(" ")
                txt[k] = v.strip()
        got = (int(txt["dexmin"]), [int(v) for v in txt["acts"].split()],
               int(txt["actmon"]), txt["seq"].split())
        want = (want_min, want_acts, want_amon, want_seq)
        if got == want:
            print("%-8s 몬민첩 %2d  최저 %2d  행동수 %s 몬%d  순서 %d 개  OK"
                  % (name, mondex, want_min, want_acts, want_amon, len(want_seq)))
            continue
        bad += 1
        print("%-8s MISMATCH (몬스터 종류 %d, 민첩 %d)" % (name, kind, mondex))
        for lab, g, wv in zip(("최저민첩", "행동수", "몬행동수", "순서"), got, want):
            mark = "OK" if g == wv else "다름"
            print("   %-8s %s  롬 %s" % (lab, mark, g))
            if g != wv:
                print("   %-8s     모델 %s" % ("", wv))
    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1


# --------------------------------------------------------------------------
# 명령이 실제로 상태를 바꾸는가 - 방어(DEFEND)
# --------------------------------------------------------------------------
# 주사위를 안 굴리는 유일한 명령이라 결과가 확정적이다. 여섯 명 모두 민첩이 같게
# 해서 한 바퀴만 돌게 하고, 라운드가 끝난 뒤 P_GUARD 가 전부 4 인지 본다.
# (내 다음 차례가 오면 풀리므로 한 바퀴짜리 라운드여야 남아 있다.)
P_GUARD = 30
CMD_DEFEND = 1


def cmd_tcl(outdir):
    S = syms()
    w = []
    for i in range(PARTY_N):
        b = S["Party"] + i * PARTY_STRIDE
        w += ["debug write memory %d 10" % (b + P_DEX),
              "debug write memory %d %d" % (b + P_HP, BIG_HP),
              "debug write memory %d %d" % (b + P_MAXHP, BIG_HP),
              "debug write memory %d 30" % (b + P_AC),
              "debug write memory %d 0" % (b + P_GUARD)]
    for i in range(MON_N):
        b = S["Monsters"] + i * MON_STRIDE
        hp = BIG_HP if i == 0 else 0
        w += ["debug write memory %d %d" % (b + 1, hp),
              "debug write memory %d %d" % (b + 2, hp)]
    w += ["debug write memory %d 1" % S["MonCount"],
          "debug write memory %d 2" % S["MonKind"],      # DWARF 민첩 12
          "debug write memory %d 1" % S["BattleOn"],
          "debug write memory %d 1" % S["RoundNo"]]
    out = os.path.join(outdir, "defend.txt").replace(chr(92), "/")
    L = ["# defend - generated by gfx/quest_turns.py",
         'set ::fh [open "%s" w]' % out,
         "set ::go 0",
         "after time 7 { %s ; set ::go 1 }" % " ; ".join(w),
         "debug set_bp %d 1 {" % S["AskCommand"],       # 모두 방어를 고른 셈
         "  debug write memory %d [reg a]" % S["MenuHero"],
         "  set sp [reg sp]",
         "  set lo [debug read memory $sp]",
         "  set hi [debug read memory [expr $sp + 1]]",
         "  reg sp [expr $sp + 2]",
         "  reg pc [expr $lo + $hi * 256]",
         "  reg a %d" % CMD_DEFEND,
         "}",
         "debug set_bp %d 1 {" % S["MainLoop"],
         "  if {$::go != 1} { return }",
         "  set ::go 2",
         "  set sp [expr [reg sp] - 2]",
         "  debug write memory $sp %d" % (S["MainLoop"] & 0xFF),
         "  debug write memory [expr $sp + 1] %d" % (S["MainLoop"] >> 8),
         "  reg sp $sp",
         "  reg pc %d" % S["BattleRound"],
         "}",
         "after time 12 {",
         '  set g ""',
         "  for {set i 0} {$i < %d} {incr i} { append g \"[debug read memory [expr %d + $i * %d]] \" }"
         % (PARTY_N, S["Party"] + P_GUARD, PARTY_STRIDE),
         '  puts $::fh "guard $g"',
         '  puts $::fh "acts [debug read memory %d]"' % S["ActHero"],
         "  close $::fh ; exit",
         "}"]
    open(os.path.join(outdir, "defend.tcl"), "w",
         encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote defend.tcl")


def cmd_check(outdir):
    txt = {}
    for line in open(os.path.join(outdir, "defend.txt")).read().split("\n"):
        if line.strip():
            k, _, v = line.partition(" ")
            txt[k] = v.strip()
    guard = [int(v) for v in txt["guard"].split()]
    ok = guard == [4] * PARTY_N
    print("defend  P_GUARD %s  %s" % (guard, "OK" if ok else "MISMATCH (기대 %s)"
                                      % ([4] * PARTY_N)))
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


# --------------------------------------------------------------------------
# 메뉴 커서 - 좌우와 상하가 2x2 격자대로 움직이는가
# --------------------------------------------------------------------------
# 명령이 한 줄에 둘씩 놓이므로 색인의 bit0 이 열, bit1 이 줄이다. 화면만 보고는
# "화살표가 움직였다"까지만 알 수 있어서, 실제로 누른 뒤 MenuSel 을 읽어 본다.
# AskCommand 를 우회하지 않는 유일한 검사다 - 우회하면 입력 처리가 통째로 빠진다.
KEYS = {"left": "0x10", "up": "0x20", "down": "0x40", "right": "0x80"}
CURSOR_PRESSES = ["right", "down", "left", "up", "left", "up"]
CURSOR_WANT = [1, 3, 2, 0, 1, 3]


def cursor_tcl(outdir):
    S = syms()
    w = []
    for i in range(PARTY_N):
        b = S["Party"] + i * PARTY_STRIDE
        w += ["debug write memory %d 10" % (b + P_DEX),
              "debug write memory %d %d" % (b + P_HP, BIG_HP),
              "debug write memory %d %d" % (b + P_MAXHP, BIG_HP)]
    for i in range(MON_N):
        b = S["Monsters"] + i * MON_STRIDE
        hp = BIG_HP if i == 0 else 0
        w += ["debug write memory %d %d" % (b + 1, hp),
              "debug write memory %d %d" % (b + 2, hp)]
    w += ["debug write memory %d 1" % S["MonCount"],
          "debug write memory %d 2" % S["MonKind"],
          "debug write memory %d 1" % S["BattleOn"],
          "debug write memory %d 1" % S["RoundNo"]]
    out = os.path.join(outdir, "cursor.txt").replace(chr(92), "/")
    L = ["# cursor - generated by gfx/quest_turns.py",
         'set ::fh [open "%s" w]' % out,
         "set ::go 0",
         "set ::sel {}",
         "after time 7 { %s ; set ::go 1 }" % " ; ".join(w),
         "debug set_bp %d 1 {" % S["MainLoop"],
         "  if {$::go != 1} { return }",
         "  set ::go 2",
         "  set sp [expr [reg sp] - 2]",
         "  debug write memory $sp %d" % (S["MainLoop"] & 0xFF),
         "  debug write memory [expr $sp + 1] %d" % (S["MainLoop"] >> 8),
         "  reg sp $sp",
         "  reg pc %d" % S["BattleRound"],
         "}"]
    t = 8.0
    for name in CURSOR_PRESSES:                 # 누르고 떼고, 가라앉은 뒤에 읽는다
        L += ["after time %.2f { keymatrixdown 8 %s }" % (t, KEYS[name]),
              "after time %.2f { keymatrixup 8 %s }" % (t + 0.15, KEYS[name]),
              "after time %.2f { lappend ::sel [debug read memory %d] }"
              % (t + 0.35, S["MenuSel"])]
        t += 0.5
    L += ["after time %.2f {" % t,
          '  puts $::fh "sel $::sel"',
          '  puts $::fh "hero [debug read memory %d]"' % S["MenuHero"],
          "  close $::fh ; exit",
          "}"]
    open(os.path.join(outdir, "cursor.tcl"), "w",
         encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote cursor.tcl")


def cursor_check(outdir):
    txt = {}
    for line in open(os.path.join(outdir, "cursor.txt")).read().split("\n"):
        if line.strip():
            k, _, v = line.partition(" ")
            txt[k] = v.strip()
    sel = [int(v) for v in txt["sel"].split()]
    ok = sel == CURSOR_WANT
    for name, g, wv in zip(CURSOR_PRESSES, sel, CURSOR_WANT):
        print("   %-6s -> %s%s" % (name, g, "" if g == wv else "   기대 %d" % wv))
    print("cursor  %s" % ("OK" if ok else "MISMATCH (기대 %s)" % CURSOR_WANT))
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


# --------------------------------------------------------------------------
# 도망(FLEE) - 굴림이 정말 d20 + 민첩 보정인가
# --------------------------------------------------------------------------
# 방어만 검사하고 있었더니 도망의 굴림이 통째로 틀린 채로 지나갔다. RandMod 가
# 면 수를 **C** 로 받는데 A 에 넣고 있었고, RandMod 가 BC 를 뭉개는 것도 놓쳤다.
# 실측 C=0, A=85 - 12 를 넘으니 도망이 거의 언제나 성공했다.
#
# 주사위를 굴리는 명령이라 결과가 확정적이지 않지만 **입력은 확정적이다.**
# RollDie 에 들어가는 면 수가 20 인지, 더해지는 값이 민첩 보정인지를 본다.
FLEE_DEX = 18                   # 보정 +4 (AbilMod 표)
FLEE_MOD = 4
CMD_FLEE = 2


def flee_tcl(outdir):
    S = syms()
    w = []
    for i in range(PARTY_N):
        b = S["Party"] + i * PARTY_STRIDE
        w += ["debug write memory %d %d" % (b + P_DEX, FLEE_DEX),
              "debug write memory %d %d" % (b + P_HP, BIG_HP),
              "debug write memory %d %d" % (b + P_MAXHP, BIG_HP),
              "debug write memory %d 30" % (b + P_AC)]
    for i in range(MON_N):
        b = S["Monsters"] + i * MON_STRIDE
        hp = BIG_HP if i == 0 else 0
        w += ["debug write memory %d %d" % (b + 1, hp),
              "debug write memory %d %d" % (b + 2, hp)]
    w += ["debug write memory %d 1" % S["MonCount"],
          "debug write memory %d 2" % S["MonKind"],
          "debug write memory %d 1" % S["BattleOn"],
          "debug write memory %d 1" % S["RoundNo"]]
    out = os.path.join(outdir, "flee.txt").replace(chr(92), "/")
    L = ["# flee - generated by gfx/quest_turns.py",
         'set ::fh [open "%s" w]' % out,
         "set ::go 0",
         "set ::n 0",
         "set ::sides 0",
         "set ::roll 0",
         "after time 7 { %s ; set ::go 1 }" % " ; ".join(w),
         "debug set_bp %d 1 {" % S["AskCommand"],      # 모두 도망을 고른 셈
         "  debug write memory %d [reg a]" % S["MenuHero"],
         "  set sp [reg sp]",
         "  set lo [debug read memory $sp]",
         "  set hi [debug read memory [expr $sp + 1]]",
         "  reg sp [expr $sp + 2]",
         "  reg pc [expr $lo + $hi * 256]",
         "  reg a %d" % CMD_FLEE,
         "}",
         # RollDie 로 들어갈 때의 C 가 면 수다
         "debug set_bp %d 1 { set ::sides [reg c] }" % S["FleeRoll"],
         # add a,b 직전. A 가 굴림, B 가 민첩 보정이어야 한다.
         "debug set_bp %d 1 {" % S["FleeTotal"],
         # FleeTotal 은 add a,b 자리다. A 가 민첩 보정(AbilityMod 가 막 돌려준
         # 값), B 가 굴림이다. 처음에 이 둘을 거꾸로 읽어서 롬이 맞는데 검사가
         # 틀렸다 - A 가 4 로 고정이고 B 가 흔들리는 것을 보고 알았다.
         '  puts $::fh "flee sides=$::sides mod=[reg a] roll=[reg b]"',
         "  flush $::fh",
         "  incr ::n",
         "  if {$::n >= 6} { close $::fh ; exit }",
         "}",
         "debug set_bp %d 1 {" % S["MainLoop"],
         "  if {$::go != 1} { return }",
         "  set ::go 2",
         "  set sp [expr [reg sp] - 2]",
         "  debug write memory $sp %d" % (S["MainLoop"] & 0xFF),
         "  debug write memory [expr $sp + 1] %d" % (S["MainLoop"] >> 8),
         "  reg sp $sp",
         "  reg pc %d" % S["BattleRound"],
         "}",
         "after time 16 { close $::fh ; exit }"]
    open(os.path.join(outdir, "flee.tcl"), "w",
         encoding="ascii", newline="\n").write("\n".join(L) + "\n")
    print("wrote flee.tcl")


def flee_check(outdir):
    rows = []
    for line in open(os.path.join(outdir, "flee.txt")).read().split("\n"):
        if line.startswith("flee "):
            d = dict(kv.split("=") for kv in line.split()[1:])
            rows.append((int(d["sides"]), int(d["roll"]), int(d["mod"])))
    # sides=20, roll=1..20, mod=민첩 보정
    if not rows:
        print("도망 굴림을 한 번도 못 잡았다")
        return 1
    bad = 0
    for sides, roll, mod in rows:
        ok = sides == 20 and 1 <= roll <= 20 and mod == FLEE_MOD
        if not ok:
            bad += 1
        print("   면 수 %-3d 굴림 %-3d 민첩보정 %-3d  %s"
              % (sides, roll, mod, "OK" if ok else
                 "MISMATCH (면 수 20, 굴림 1~20, 보정 %d 이어야 함)" % FLEE_MOD))
    print("flee  %d 번 중 %d 번 어긋남" % (len(rows), bad))
    print("PASS" if bad == 0 else "FAIL")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    mode, outdir = sys.argv[1], sys.argv[2]
    sys.exit({"tcl": write_tcl, "check": check,
              "cmdtcl": cmd_tcl, "cmdcheck": cmd_check,
              "cursortcl": cursor_tcl, "cursorcheck": cursor_check,
              "fleetcl": flee_tcl, "fleecheck": flee_check}[mode](outdir))
